begin;
select plan(17);
select has_table('public','uber_test_offer_batches','existe tabla TEST de tandas');
select has_table('public','uber_test_offers','existe tabla TEST de ofertas');
select has_table('public','uber_test_offer_results','existe tabla TEST de resultados');
select ok((select relrowsecurity from pg_class where oid='public.uber_test_offer_batches'::regclass),'RLS tanda activo');
select ok((select relrowsecurity from pg_class where oid='public.uber_test_offers'::regclass),'RLS ofertas activo');
select ok((select relrowsecurity from pg_class where oid='public.uber_test_offer_results'::regclass),'RLS resultados activo');
select has_function('public','console_send_uber_test_batch',array['uuid','jsonb','text'],'RPC Consola disponible');
select has_function('public','record_uber_test_result',array['uuid','text','text'],'RPC resultado disponible');
select has_function('public','driver_get_uber_test_batch',ARRAY['text']::text[],'RPC recuperacion exige installation_id');
select ok(not has_function('public','driver_get_uber_test_batch',array[]::text[]),'RPC legacy sin installation_id eliminado');
select has_function('public','present_next_uber_test_offer',array['uuid'],'RPC presentacion secuencial disponible');
select has_table('public','uber_test_offer_events','existe evento fuente TEST para integracion');
select ok((select count(*) from information_schema.columns where table_schema='public' and table_name='uber_test_offer_events' and column_name in ('presented_offer_id','presented_at','copilot_status'))=3,'evento expone estado de presentacion Copiloto');
select ok(not has_table_privilege('anon','public.uber_test_offer_batches','SELECT'),'anon no lee tandas');
select ok(not has_table_privilege('anon','public.uber_test_offer_results','INSERT'),'anon no inserta resultados');
select ok((select count(*) from pg_indexes where schemaname='public' and tablename='uber_test_offer_events' and indexname='uber_test_offer_events_presented_offer_idx')=1,'indice de oferta presentada');
select ok(has_function('public','record_uber_test_result',array['uuid','text','text']),'resultado conserva RPC canonico');
select * from finish();
rollback;
