import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

import {
  canBookRecovery,
  evaluateBonuses,
  bonusDefinition,
  monthKey,
  pendingBonusAlert,
  type BonusAlert,
  type BonusEvaluation,
} from "@/lib/bonuses";
import { CREDIT_PROGRAM, creditMetrics, newCreditAccount, type CreditMetrics } from "@/lib/credit";
import { dateShort, firstName } from "@/lib/format";
import {
  accountById,
  ROLE,
  stationById,
  type SignInMethod,
  type StaffAccount,
  type StaffRole,
  type StaffSession,
  type Station,
} from "@/lib/org";
import {
  buildCreditAccount,
  buildIncidents,
  buildIncomeHistory,
  buildNotices,
  buildShiftHistory,
  buildSupervisorReports,
  MOCK_DRIVER,
  MOCK_VEHICLES,
  syncVehicleOdometers,
} from "@/lib/mock";
import {
  goalsFor,
  groupForDate,
  lateMinutesFor,
  scheduledStart,
  SLOT_LABEL,
  SLOT_RANGE_LABEL,
} from "@/lib/schedule";
import { weeklyLateBreakdown, weeklyLateDebt } from "@/lib/selectors";
import { loadState, saveState } from "@/lib/storage";
import type {
  ActiveShift,
  BonusKind,
  CreditAccount,
  Driver,
  IncomeEntry,
  IncomePlatform,
  Incident,
  IncidentKind,
  Notice,
  NoticeKind,
  PhotoSlotId,
  RecoveryBooking,
  ShiftPhotos,
  ShiftRecord,
  ShiftSlot,
  ShiftSummary,
  SupervisorReport,
  Vehicle,
} from "@/lib/types";

const STATE_KEY = "state.v4";

/** Average fleet speed used to estimate distance until real GPS/telemetry lands. */
const SIMULATED_KM_PER_MINUTE = 0.32;

interface PersistedState {
  /** Active session; its role is the single gate that opens an interface. */
  session: StaffSession | null;
  /** Credential linked to this device for biometric unlock. */
  enrolledAccountId: string | null;
  vehicles: Vehicle[];
  activeShift: ActiveShift | null;
  history: ShiftRecord[];
  incomes: IncomeEntry[];
  incidents: Incident[];
  notices: Notice[];
  /** Used-unit credit contract; `null` while the driver has not signed one. */
  credit: CreditAccount | null;
  clockOffsetMinutes: number;
  /** Reports generated by the station supervisor; they break the vehicle-care bonus. */
  supervisorReports: SupervisorReport[];
  /** Days reserved in the bonus recovery program. */
  recoveryBookings: RecoveryBooking[];
  /** Bonus weeks already announced, so the popup is shown only once. */
  notifiedBonusWeeks: string[];
}

const buildInitialState = (): PersistedState => {
  const now = new Date();
  const history = buildShiftHistory(MOCK_DRIVER, now);
  return {
    session: null,
    enrolledAccountId: null,
    vehicles: syncVehicleOdometers(MOCK_VEHICLES, history),
    activeShift: null,
    history,
    incomes: buildIncomeHistory(MOCK_DRIVER, history),
    incidents: buildIncidents(MOCK_DRIVER, now),
    notices: buildNotices(now),
    credit: null,
    clockOffsetMinutes: 0,
    supervisorReports: buildSupervisorReports(now),
    recoveryBookings: [],
    notifiedBonusWeeks: [],
  };
};

export interface AssignVehicleInput {
  vehicle: Vehicle;
  odometerKm: number;
  batteryPct: number;
}

interface FleetContextValue {
  driver: Driver;
  now: Date;
  isAuthenticated: boolean;
  session: StaffSession | null;
  /** Authenticated credential, or null when there is no session. */
  account: StaffAccount | null;
  role: StaffRole | null;
  station: Station | null;
  /** Credential allowed to unlock this device with biometrics. */
  enrolledAccount: StaffAccount | null;
  /** Interfaces open by role only: a driver can never render a supervisor screen. */
  hasAccess: (role: StaffRole) => boolean;
  vehicles: Vehicle[];
  activeShift: ActiveShift | null;
  activeVehicle: Vehicle | null;
  history: ShiftRecord[];
  incomes: IncomeEntry[];
  incidents: Incident[];
  notices: Notice[];
  credit: CreditAccount | null;
  creditMetrics: CreditMetrics | null;
  clockOffsetMinutes: number;
  supervisorReports: SupervisorReport[];
  recoveryBookings: RecoveryBooking[];
  bonusEvaluations: BonusEvaluation[];
  bonusPayableMxn: number;
  unreadNotices: number;
  weeklyLateDebtMinutes: number;
  elapsedSeconds: number;
  estimatedKmDriven: number;
  signIn: (account: StaffAccount, method: SignInMethod) => void;
  signOut: () => void;
  /** Removes the biometric link so the next access requires full credentials. */
  forgetDevice: () => void;
  setClockOffset: (minutes: number) => void;
  resetDemoData: () => void;
  assignVehicle: (input: AssignVehicleInput) => ActiveShift;
  saveInspectionPhoto: (slot: PhotoSlotId, dataUrl: string) => void;
  registerIncome: (input: {
    amountMxn: number;
    trips: number;
    platform: IncomePlatform;
    evidence?: string;
    note?: string;
  }) => void;
  addTrip: () => void;
  reportIncident: (input: { kind: IncidentKind; description: string; photos: string[] }) => void;
  finishShift: (input: { endOdometerKm: number; endBatteryPct: number; photo?: string }) => ShiftSummary;
  payLateTime: (minutes: number) => number;
  markNoticeRead: (id: string) => void;
  markAllNoticesRead: () => void;
  pushNotice: (input: { kind: NoticeKind; title: string; body: string }) => void;
  /** Raises the weekly cut-off popup for the first bonus week lost, once only. */
  raiseBonusAlert: () => BonusAlert | null;
  bookRecovery: (input: { date: Date; slot: ShiftSlot; bonus: BonusKind }) => boolean;
  cancelRecovery: (id: string) => void;
  /** Signs a new contract: no down payment, immediate approval. */
  requestCredit: () => void;
  /** Loads the seeded mid-term contract so every metric can be reviewed. */
  loadCreditDemoProgress: () => void;
  /** Returns the driver to the promotional banner state. */
  cancelCredit: () => void;
}

const FleetContext = createContext<FleetContextValue | null>(null);

const createId = (prefix: string): string => `${prefix}-${Math.random().toString(36).slice(2, 9)}`;

export const FleetProvider = ({ children }: { children: ReactNode }) => {
  const [state, setState] = useState<PersistedState>(() => loadState<PersistedState>(STATE_KEY) ?? buildInitialState());
  const [tick, setTick] = useState<number>(() => Date.now());

  useEffect(() => {
    const interval = window.setInterval(() => setTick(Date.now()), 1000);
    return () => window.clearInterval(interval);
  }, []);

  useEffect(() => {
    saveState(STATE_KEY, state);
  }, [state]);

  const driver = MOCK_DRIVER;

  /** Device clock, shifted by the demo offset so any shift window can be reviewed. */
  const now = useMemo(() => new Date(tick + state.clockOffsetMinutes * 60000), [tick, state.clockOffsetMinutes]);

  const activeVehicle = useMemo(
    () => state.vehicles.find((vehicle) => vehicle.id === state.activeShift?.vehicleId) ?? null,
    [state.vehicles, state.activeShift],
  );

  const elapsedSeconds = useMemo(() => {
    if (!state.activeShift) return 0;
    return Math.max(0, Math.floor((now.getTime() - new Date(state.activeShift.startedAt).getTime()) / 1000));
  }, [state.activeShift, now]);

  const estimatedKmDriven = useMemo(
    () => Math.round((elapsedSeconds / 60) * SIMULATED_KM_PER_MINUTE),
    [elapsedSeconds],
  );

  const unreadNotices = useMemo(() => state.notices.filter((notice) => !notice.read).length, [state.notices]);

  const weeklyLateDebtMinutes = useMemo(() => weeklyLateDebt(state.history, now), [state.history, now]);

  const metrics = useMemo<CreditMetrics | null>(
    () => (state.credit ? creditMetrics(state.credit, now) : null),
    [state.credit, now],
  );

  const account = useMemo(() => accountById(state.session?.accountId), [state.session]);
  const enrolledAccount = useMemo(() => accountById(state.enrolledAccountId), [state.enrolledAccountId]);
  const station = useMemo(() => stationById(state.session?.stationId), [state.session]);
  const hasAccess = useCallback(
    (target: StaffRole): boolean => state.session?.role === target,
    [state.session],
  );

  const signIn = useCallback((account: StaffAccount, method: SignInMethod) => {
    setState((prev) => ({
      ...prev,
      session: {
        accountId: account.id,
        role: account.role,
        stationId: account.stationId,
        method,
        startedAt: new Date().toISOString(),
      },
      enrolledAccountId: account.id,
    }));
  }, []);
  const signOut = useCallback(() => setState((prev) => ({ ...prev, session: null })), []);
  const forgetDevice = useCallback(
    () => setState((prev) => ({ ...prev, session: null, enrolledAccountId: null })),
    [],
  );
  const setClockOffset = useCallback(
    (minutes: number) => setState((prev) => ({ ...prev, clockOffsetMinutes: minutes })),
    [],
  );
  const resetDemoData = useCallback(
    () =>
      setState((prev) => ({
        ...buildInitialState(),
        session: prev.session,
        enrolledAccountId: prev.enrolledAccountId,
      })),
    [],
  );

  const pushNotice = useCallback(({ kind, title, body }: { kind: NoticeKind; title: string; body: string }) => {
    setState((prev) => ({
      ...prev,
      notices: [
        { id: createId("not"), kind, title, body, createdAt: new Date().toISOString(), read: false },
        ...prev.notices,
      ],
    }));
  }, []);

  const assignVehicle = useCallback(
    ({ vehicle, odometerKm, batteryPct }: AssignVehicleInput): ActiveShift => {
      const startedAt = new Date(Date.now() + state.clockOffsetMinutes * 60000);
      const group = groupForDate(startedAt);
      const scheduled = scheduledStart(driver.shift.slot, startedAt);
      const shift: ActiveShift = {
        id: createId("shift"),
        driverId: driver.id,
        vehicleId: vehicle.id,
        group,
        slot: driver.shift.slot,
        scheduledStartAt: scheduled.toISOString(),
        startedAt: startedAt.toISOString(),
        lateMinutes: lateMinutesFor(scheduled, startedAt),
        startOdometerKm: odometerKm,
        startBatteryPct: batteryPct,
        photos: {},
        trips: 0,
        earningsMxn: 0,
        kmDriven: 0,
      };

      setState((prev) => ({
        ...prev,
        activeShift: shift,
        vehicles: prev.vehicles.map((item) =>
          item.id === vehicle.id
            ? { ...item, status: "occupied", occupiedBy: driver.id, odometerKm, batteryPct }
            : item,
        ),
      }));

      return shift;
    },
    [driver, state.clockOffsetMinutes],
  );

  const saveInspectionPhoto = useCallback((slot: PhotoSlotId, dataUrl: string) => {
    setState((prev) => {
      if (!prev.activeShift) return prev;
      const photos: ShiftPhotos = { ...prev.activeShift.photos, [slot]: dataUrl };
      return { ...prev, activeShift: { ...prev.activeShift, photos } };
    });
  }, []);

  const registerIncome = useCallback<FleetContextValue["registerIncome"]>(
    ({ amountMxn, trips, platform, evidence, note }) => {
      setState((prev) => {
        const entry: IncomeEntry = {
          id: createId("inc"),
          driverId: driver.id,
          shiftId: prev.activeShift?.id ?? null,
          date: new Date(Date.now() + prev.clockOffsetMinutes * 60000).toISOString(),
          amountMxn,
          trips,
          platform,
          evidence,
          note,
        };
        return {
          ...prev,
          incomes: [entry, ...prev.incomes],
          activeShift: prev.activeShift
            ? {
                ...prev.activeShift,
                earningsMxn: prev.activeShift.earningsMxn + amountMxn,
                trips: prev.activeShift.trips + trips,
              }
            : prev.activeShift,
        };
      });
    },
    [driver.id],
  );

  const addTrip = useCallback(() => {
    setState((prev) =>
      prev.activeShift
        ? { ...prev, activeShift: { ...prev.activeShift, trips: prev.activeShift.trips + 1 } }
        : prev,
    );
  }, []);

  const reportIncident = useCallback<FleetContextValue["reportIncident"]>(
    ({ kind, description, photos }) => {
      setState((prev) => {
        const vehicle = prev.vehicles.find((item) => item.id === prev.activeShift?.vehicleId) ?? prev.vehicles[0];
        const incident: Incident = {
          id: createId("inci"),
          driverId: driver.id,
          vehicleId: vehicle.id,
          vehicleInternalNumber: vehicle.internalNumber,
          kind,
          createdAt: new Date(Date.now() + prev.clockOffsetMinutes * 60000).toISOString(),
          description,
          photos,
          status: "open",
        };
        return { ...prev, incidents: [incident, ...prev.incidents] };
      });
    },
    [driver.id],
  );

  const finishShift = useCallback<FleetContextValue["finishShift"]>(
    ({ endOdometerKm, endBatteryPct, photo }) => {
      const shift = state.activeShift;
      const goals = goalsFor(driver.shift.group);
      if (!shift) {
        return {
          kmDriven: 0,
          durationMinutes: 0,
          earningsMxn: 0,
          trips: 0,
          dailyGoalMxn: goals.dailyMxn,
          missingMxn: goals.dailyMxn,
          missingTrips: goals.tripsPerDay,
          lateMinutes: 0,
        };
      }

      const endedAt = new Date(Date.now() + state.clockOffsetMinutes * 60000);
      const durationMinutes = Math.max(
        0,
        Math.round((endedAt.getTime() - new Date(shift.startedAt).getTime()) / 60000),
      );
      const kmDriven = Math.max(0, Math.round(endOdometerKm - shift.startOdometerKm));

      const record: ShiftRecord = {
        id: shift.id,
        driverId: shift.driverId,
        vehicleId: shift.vehicleId,
        vehicleInternalNumber:
          state.vehicles.find((item) => item.id === shift.vehicleId)?.internalNumber ?? "—",
        group: shift.group,
        slot: shift.slot,
        scheduledStartAt: shift.scheduledStartAt,
        startedAt: shift.startedAt,
        endedAt: endedAt.toISOString(),
        lateMinutes: shift.lateMinutes,
        paidBackMinutes: 0,
        startOdometerKm: shift.startOdometerKm,
        endOdometerKm,
        startBatteryPct: shift.startBatteryPct,
        endBatteryPct,
        trips: shift.trips,
        earningsMxn: shift.earningsMxn,
        photos: photo ? { ...shift.photos, odometer: photo } : shift.photos,
      };

      setState((prev) => ({
        ...prev,
        activeShift: null,
        history: [record, ...prev.history],
        vehicles: prev.vehicles.map((item) =>
          item.id === shift.vehicleId
            ? { ...item, status: "available", occupiedBy: null, odometerKm: endOdometerKm, batteryPct: endBatteryPct }
            : item,
        ),
      }));

      return {
        kmDriven,
        durationMinutes,
        earningsMxn: shift.earningsMxn,
        trips: shift.trips,
        dailyGoalMxn: goals.dailyMxn,
        missingMxn: Math.max(0, goals.dailyMxn - shift.earningsMxn),
        missingTrips: Math.max(0, goals.tripsPerDay - shift.trips),
        lateMinutes: shift.lateMinutes,
      };
    },
    [state.activeShift, state.vehicles, state.clockOffsetMinutes, driver.shift.group],
  );

  /** Applies paid-back minutes to the oldest pending late day of the current week. */
  const payLateTime = useCallback(
    (minutes: number): number => {
      let applied = 0;
      setState((prev) => {
        const week = weeklyLateBreakdown(prev.history, new Date(Date.now() + prev.clockOffsetMinutes * 60000));
        const pendingIds = new Set(
          week
            .filter((day) => day.minutes - day.paidBackMinutes > 0)
            .map((day) => prev.history.find((record) => record.startedAt.startsWith(
              day.date.toISOString().slice(0, 10),
            ))?.id)
            .filter((id): id is string => Boolean(id)),
        );

        let remaining = minutes;
        const history = prev.history.map((record) => {
          if (remaining <= 0 || !pendingIds.has(record.id)) return record;
          const pending = Math.max(0, record.lateMinutes - record.paidBackMinutes);
          const pay = Math.min(pending, remaining);
          remaining -= pay;
          applied += pay;
          return { ...record, paidBackMinutes: record.paidBackMinutes + pay };
        });

        return { ...prev, history };
      });
      return applied;
    },
    [],
  );

  const markNoticeRead = useCallback((id: string) => {
    setState((prev) => ({
      ...prev,
      notices: prev.notices.map((notice) => (notice.id === id ? { ...notice, read: true } : notice)),
    }));
  }, []);

  const markAllNoticesRead = useCallback(() => {
    setState((prev) => ({ ...prev, notices: prev.notices.map((notice) => ({ ...notice, read: true })) }));
  }, []);

  const bonusEvaluations = useMemo(
    () =>
      evaluateBonuses({
        driver,
        history: state.history,
        incomes: state.incomes,
        reports: state.supervisorReports,
        now,
      }),
    [driver, state.history, state.incomes, state.supervisorReports, now],
  );

  const bonusPayableMxn = useMemo(
    () => bonusEvaluations.reduce((total, item) => total + item.payableMxn, 0),
    [bonusEvaluations],
  );

  const raiseBonusAlert = useCallback((): BonusAlert | null => {
    const reference = new Date(Date.now() + state.clockOffsetMinutes * 60000);
    const evaluations = evaluateBonuses({
      driver,
      history: state.history,
      incomes: state.incomes,
      reports: state.supervisorReports,
      now: reference,
    });
    const alert = pendingBonusAlert(
      evaluations,
      state.notifiedBonusWeeks,
      firstName(driver.name),
      reference,
    );
    if (!alert) return null;

    const week = evaluations
      .find((item) => item.kind === alert.kind)
      ?.weeks.find((item) => item.week.index === alert.weekIndex);

    setState((prev) => ({
      ...prev,
      notifiedBonusWeeks: [...prev.notifiedBonusWeeks, alert.id],
      notices: [
        {
          id: createId("not"),
          kind: "reminder",
          title: alert.message,
          body: `Semana ${alert.weekIndex} evaluada: ${week?.detail ?? "meta no alcanzada"}.`,
          createdAt: new Date().toISOString(),
          read: false,
        },
        ...prev.notices,
      ],
    }));

    return alert;
  }, [
    driver,
    state.clockOffsetMinutes,
    state.history,
    state.incomes,
    state.notifiedBonusWeeks,
    state.supervisorReports,
  ]);

  const bookRecovery = useCallback<FleetContextValue["bookRecovery"]>(
    ({ date, slot, bonus }) => {
      const reference = new Date(Date.now() + state.clockOffsetMinutes * 60000);
      if (!canBookRecovery(driver, date, reference)) return false;

      const day = new Date(date);
      day.setHours(0, 0, 0, 0);
      const alreadyBooked = state.recoveryBookings.some(
        (item) => new Date(item.date).toDateString() === day.toDateString(),
      );
      if (alreadyBooked) return false;

      const booking: RecoveryBooking = {
        id: createId("rec"),
        date: day.toISOString(),
        slot,
        bonus,
        createdAt: reference.toISOString(),
      };
      const label = dateShort(day);

      setState((prev) => ({
        ...prev,
        recoveryBookings: [...prev.recoveryBookings, booking],
        notices: [
          {
            id: createId("not"),
            kind: "station",
            title: "Reserva confirmada en recuperación de bonos",
            body: `${label.charAt(0).toUpperCase()}${label.slice(1)} · turno ${SLOT_LABEL[slot].toLowerCase()} ${SLOT_RANGE_LABEL[slot]}. Recuperas el bono de ${bonusDefinition(bonus).shortName}.`,
            createdAt: reference.toISOString(),
            read: false,
          },
          ...prev.notices,
        ],
      }));
      return true;
    },
    [driver, state.clockOffsetMinutes, state.recoveryBookings],
  );

  const requestCredit = useCallback(() => {
    setState((prev) => {
      if (prev.credit) return prev;
      const reference = new Date(Date.now() + prev.clockOffsetMinutes * 60000);
      const unit =
        prev.vehicles.find((vehicle) => MOCK_DRIVER.authorizedVehicleIds.includes(vehicle.id))?.internalNumber ??
        "por asignar";
      return {
        ...prev,
        credit: newCreditAccount(reference, unit),
        notices: [
          {
            id: createId("not"),
            kind: "credit",
            title: "Crédito aprobado",
            body: `Tu contrato del ${CREDIT_PROGRAM.vehicleModel} quedó firmado. El primer abono semanal se descuenta en 7 días.`,
            createdAt: reference.toISOString(),
            read: false,
          },
          ...prev.notices,
        ],
      };
    });
  }, []);

  const loadCreditDemoProgress = useCallback(() => {
    setState((prev) => ({
      ...prev,
      credit: buildCreditAccount(new Date(Date.now() + prev.clockOffsetMinutes * 60000)),
    }));
  }, []);

  const cancelCredit = useCallback(() => {
    setState((prev) => ({ ...prev, credit: null }));
  }, []);

  const cancelRecovery = useCallback((id: string) => {
    setState((prev) => ({
      ...prev,
      recoveryBookings: prev.recoveryBookings.filter((item) => item.id !== id),
    }));
  }, []);

  const value = useMemo<FleetContextValue>(
    () => ({
      driver,
      now,
      isAuthenticated: state.session !== null,
      session: state.session,
      account,
      role: state.session?.role ?? null,
      station,
      enrolledAccount,
      hasAccess,
      vehicles: state.vehicles,
      activeShift: state.activeShift,
      activeVehicle,
      history: state.history,
      incomes: state.incomes,
      incidents: state.incidents,
      notices: state.notices,
      credit: state.credit,
      creditMetrics: metrics,
      clockOffsetMinutes: state.clockOffsetMinutes,
      supervisorReports: state.supervisorReports,
      recoveryBookings: state.recoveryBookings,
      bonusEvaluations,
      bonusPayableMxn,
      unreadNotices,
      weeklyLateDebtMinutes,
      elapsedSeconds,
      estimatedKmDriven,
      signIn,
      signOut,
      forgetDevice,
      setClockOffset,
      resetDemoData,
      assignVehicle,
      saveInspectionPhoto,
      registerIncome,
      addTrip,
      reportIncident,
      finishShift,
      payLateTime,
      markNoticeRead,
      markAllNoticesRead,
      pushNotice,
      raiseBonusAlert,
      bookRecovery,
      cancelRecovery,
      requestCredit,
      loadCreditDemoProgress,
      cancelCredit,
    }),
    [
      driver,
      now,
      state.session,
      account,
      station,
      enrolledAccount,
      hasAccess,
      state.vehicles,
      state.activeShift,
      state.history,
      state.incomes,
      state.incidents,
      state.notices,
      state.credit,
      metrics,
      state.clockOffsetMinutes,
      state.supervisorReports,
      state.recoveryBookings,
      bonusEvaluations,
      bonusPayableMxn,
      activeVehicle,
      unreadNotices,
      weeklyLateDebtMinutes,
      elapsedSeconds,
      estimatedKmDriven,
      signIn,
      signOut,
      forgetDevice,
      setClockOffset,
      resetDemoData,
      assignVehicle,
      saveInspectionPhoto,
      registerIncome,
      addTrip,
      reportIncident,
      finishShift,
      payLateTime,
      markNoticeRead,
      markAllNoticesRead,
      pushNotice,
      raiseBonusAlert,
      bookRecovery,
      cancelRecovery,
      requestCredit,
      loadCreditDemoProgress,
      cancelCredit,
    ],
  );

  return <FleetContext.Provider value={value}>{children}</FleetContext.Provider>;
};

export const useFleet = (): FleetContextValue => {
  const context = useContext(FleetContext);
  if (!context) throw new Error("useFleet debe usarse dentro de FleetProvider");
  return context;
};
