/** Domain model for the Turno EV fleet driver app. All data is mock data today;
 *  every type is shaped so it can be fed later by a real API (Uber, GPS, OCR, telemetry). */

export type ShiftGroup = "weekday" | "weekend";
export type ShiftSlot = "morning" | "evening";

export interface ShiftAssignment {
  group: ShiftGroup;
  slot: ShiftSlot;
}

export interface Driver {
  id: string;
  name: string;
  employeeNumber: string;
  email: string;
  password: string;
  photoUrl: string;
  /** Station the driver belongs to; work can only start in this station. */
  stationId: string;
  station: string;
  shift: ShiftAssignment;
  /** Units this driver is authorized to operate. */
  authorizedVehicleIds: string[];
}

export type VehicleStatus = "available" | "occupied" | "maintenance";

export interface Vehicle {
  id: string;
  /** QR payload printed on the windshield sticker. */
  qrCode: string;
  internalNumber: string;
  model: string;
  plates: string;
  /** Odometer registered at the end of the previous shift. */
  odometerKm: number;
  batteryPct: number;
  stationId: string;
  station: string;
  status: VehicleStatus;
  occupiedBy: string | null;
  photoUrl: string;
}

export type PhotoSlotId = "odometer" | "battery" | "front" | "left" | "right" | "rear";

/** Base64/object URLs of captured evidence, keyed by inspection slot. */
export type ShiftPhotos = Partial<Record<PhotoSlotId, string>>;

export interface ActiveShift {
  id: string;
  driverId: string;
  vehicleId: string;
  group: ShiftGroup;
  slot: ShiftSlot;
  /** ISO timestamps. */
  scheduledStartAt: string;
  startedAt: string;
  lateMinutes: number;
  startOdometerKm: number;
  startBatteryPct: number;
  photos: ShiftPhotos;
  trips: number;
  earningsMxn: number;
  kmDriven: number;
}

export interface ShiftRecord {
  id: string;
  driverId: string;
  vehicleId: string;
  vehicleInternalNumber: string;
  group: ShiftGroup;
  slot: ShiftSlot;
  scheduledStartAt: string;
  startedAt: string;
  endedAt: string;
  lateMinutes: number;
  /** Minutes of late time already paid back in an authorized window. */
  paidBackMinutes: number;
  startOdometerKm: number;
  endOdometerKm: number;
  startBatteryPct: number;
  endBatteryPct: number;
  trips: number;
  earningsMxn: number;
  photos: ShiftPhotos;
}

export type IncomePlatform = "Uber" | "DiDi" | "Efectivo" | "Otro";

export interface IncomeEntry {
  id: string;
  driverId: string;
  shiftId: string | null;
  date: string;
  amountMxn: number;
  trips: number;
  platform: IncomePlatform;
  /** Screenshot evidence of the platform earnings. */
  evidence?: string;
  note?: string;
}

export type IncidentKind = "accident" | "damage" | "mechanical";
export type IncidentStatus = "open" | "review" | "closed";

export interface Incident {
  id: string;
  driverId: string;
  vehicleId: string;
  vehicleInternalNumber: string;
  kind: IncidentKind;
  createdAt: string;
  description: string;
  photos: string[];
  status: IncidentStatus;
}

export type NoticeKind = "maintenance" | "credit" | "station" | "reminder";

export interface Notice {
  id: string;
  kind: NoticeKind;
  title: string;
  body: string;
  createdAt: string;
  read: boolean;
}

export type CreditStatus = "paid" | "due" | "late";

export interface CreditPayment {
  id: string;
  concept: string;
  dueDate: string;
  amountMxn: number;
  status: CreditStatus;
}

export interface CreditAccount {
  contractId: string;
  vehicleTarget: string;
  /** ISO date of the contract signature; delivery month and term are measured from here. */
  startedAt: string;
  totalMxn: number;
  paidMxn: number;
  weeklyMxn: number;
  weeksPaid: number;
  onTimePayments: number;
  latePayments: number;
  /** Odometer of the unit reserved for this contract; it leaves the fleet at 110,000-120,000 km. */
  assignedVehicleOdometerKm: number;
  payments: CreditPayment[];
}

export type BonusKind = "punctuality" | "billing" | "care" | "service";

export type SupervisorReportKind = "damage" | "cleanliness";

/** Report generated by the station supervisor against the driver. */
export interface SupervisorReport {
  id: string;
  kind: SupervisorReportKind;
  createdAt: string;
  vehicleInternalNumber: string;
  note: string;
}

/** Reserved day inside the bonus recovery program, always on the opposite group. */
export interface RecoveryBooking {
  id: string;
  date: string;
  slot: ShiftSlot;
  bonus: BonusKind;
  createdAt: string;
}

/** Blocking reasons returned before a vehicle can be assigned. */
export type AssignmentIssueCode =
  | "other_station"
  | "vehicle_occupied"
  | "invalid_shift"
  | "not_authorized"
  | "low_battery"
  | "odometer_mismatch";

export interface AssignmentIssue {
  code: AssignmentIssueCode;
  message: string;
}

export interface ShiftSummary {
  kmDriven: number;
  durationMinutes: number;
  earningsMxn: number;
  trips: number;
  dailyGoalMxn: number;
  missingMxn: number;
  missingTrips: number;
  lateMinutes: number;
}
