package com.rork.turnoevandroid.domain

import com.rork.turnoevandroid.util.Fmt
import com.rork.turnoevandroid.util.plusDays
import com.rork.turnoevandroid.util.startOfDay
import kotlinx.serialization.Serializable
import java.util.Calendar

/**
 * Monthly bonuses paid at month end but evaluated week by week: the driver must
 * hit the target on all four weeks of the month to collect.
 */

@Serializable
enum class BonusKind {
    PUNCTUALITY,
    BILLING,
    CARE,
    SERVICE;

    val title: String
        get() = when (this) {
            PUNCTUALITY -> "Puntualidad y asistencia"
            BILLING -> "Facturación"
            CARE -> "Limpieza y cuidado"
            SERVICE -> "Calidad en el servicio"
        }

    /** Short name used inside notifications: "has perdido el bono de puntualidad". */
    val shortName: String
        get() = when (this) {
            PUNCTUALITY -> "puntualidad"
            BILLING -> "facturación"
            CARE -> "limpieza"
            SERVICE -> "calidad"
        }

    val monthlyMxn: Int
        get() = when (this) {
            PUNCTUALITY -> 1_500
            BILLING -> 1_500
            CARE -> 1_000
            SERVICE -> 0
        }

    /** Quality comes from the Uber API, so the amount is defined by the platform. */
    val isExternal: Boolean get() = this == SERVICE

    val howToWin: String
        get() = when (this) {
            PUNCTUALITY -> "Inicia turno a tiempo todos los días del mes."
            BILLING -> "Llega a la meta semanal de facturación las 4 semanas."
            CARE -> "Termina el mes sin reportes de daño ni de limpieza."
            SERVICE -> "Mantén tu calificación de plataforma en verde."
        }

    val howToLose: String
        get() = when (this) {
            PUNCTUALITY -> "Se pierde con una falta o si cierras el mes con tiempo adeudado."
            BILLING -> "Se pierde en la semana que no alcanzas la meta."
            CARE -> "Se pierde si el supervisor genera un reporte en tu contra."
            SERVICE -> "Se integra con la API de Uber; en pruebas se muestra positiva."
        }
}

enum class BonusWeekStatus {
    ACHIEVED,
    LOST,
    IN_PROGRESS,
    UPCOMING;

    val label: String
        get() = when (this) {
            ACHIEVED -> "Cumplida"
            LOST -> "Perdida"
            IN_PROGRESS -> "En curso"
            UPCOMING -> "Por evaluar"
        }
}

/** Monday → Sunday evaluation window, numbered 1 to 4 inside the month. */
data class BonusWeekRange(
    val index: Int,
    val start: Long,
    val end: Long,
) {
    val shortLabel: String get() = "S$index"
    val rangeLabel: String get() = "${Fmt.dayNumber(start)} — ${Fmt.dayNumber(end - 86_400_000L)}"

    operator fun contains(millis: Long): Boolean = millis >= start && millis < end
}

data class BonusWeekResult(
    val week: BonusWeekRange,
    val status: BonusWeekStatus,
    val detail: String,
)

data class BonusEvaluation(
    val kind: BonusKind,
    val weeks: List<BonusWeekResult>,
) {
    val lostWeeks: List<Int> get() = weeks.filter { it.status == BonusWeekStatus.LOST }.map { it.week.index }
    val achievedCount: Int get() = weeks.count { it.status == BonusWeekStatus.ACHIEVED }
    val isLost: Boolean get() = lostWeeks.isNotEmpty()
    val isSecured: Boolean get() = weeks.isNotEmpty() && achievedCount == weeks.size

    /** Money actually payable at month end with the current evaluation. */
    val payableMxn: Int get() = if (isLost) 0 else kind.monthlyMxn

    val statusText: String
        get() = when {
            isLost -> "Perdido · semana ${lostWeeks.joinToString(", ")}"
            isSecured -> "Asegurado"
            else -> "En camino · $achievedCount de ${weeks.size} semanas"
        }
}

@Serializable
enum class SupervisorReportKind {
    DAMAGE,
    CLEANLINESS;

    val label: String
        get() = when (this) {
            DAMAGE -> "Reporte de daño"
            CLEANLINESS -> "Reporte de limpieza"
        }
}

/** Report generated by the station supervisor against the driver. */
@Serializable
data class SupervisorReport(
    val id: String,
    val kind: SupervisorReportKind,
    val createdAt: Long,
    val vehicleInternalNumber: String,
    val note: String,
)

/** Reserved day inside the bonus recovery program, always on the opposite group. */
@Serializable
data class RecoveryBooking(
    val id: String,
    val date: Long,
    val slot: ShiftSlot,
    val bonus: BonusKind,
    val createdAt: Long,
)

data class BonusAlert(
    val id: String,
    val kind: BonusKind,
    val weekIndex: Int,
    val message: String,
)

object BonusRules {
    /** The month is evaluated in four Monday → Sunday windows. */
    const val WEEKS_PER_MONTH = 4

    /** Uber quality score is mocked as positive until the API is connected. */
    const val MOCK_QUALITY_SCORE = 4.91

    fun monthStart(millis: Long): Long = Fmt.calendar(millis).apply {
        set(Calendar.DAY_OF_MONTH, 1)
        set(Calendar.HOUR_OF_DAY, 0)
        set(Calendar.MINUTE, 0)
        set(Calendar.SECOND, 0)
        set(Calendar.MILLISECOND, 0)
    }.timeInMillis

    fun weeks(reference: Long): List<BonusWeekRange> {
        var start = ShiftRules.weekStart(monthStart(reference))
        val result = mutableListOf<BonusWeekRange>()
        for (index in 1..WEEKS_PER_MONTH) {
            val end = start.plusDays(7)
            result += BonusWeekRange(index, start, end)
            start = end
        }
        return result
    }

    /** Days of the week the driver was scheduled to work and that already finished. */
    fun expectedWorkDays(driver: Driver, week: BonusWeekRange, now: Long): Int {
        var count = 0
        for (offset in 0 until 7) {
            val day = week.start.plusDays(offset)
            if (ShiftRules.group(day) != driver.group) continue
            if (day.plusDays(1) > now) continue
            count += 1
        }
        return count
    }

    data class EvaluationInput(
        val driver: Driver,
        val goals: ShiftRules.Goals,
        val history: List<ShiftRecord>,
        val incomes: List<IncomeEntry>,
        val reports: List<SupervisorReport>,
        val now: Long,
    )

    fun evaluateAll(input: EvaluationInput): List<BonusEvaluation> {
        val ranges = weeks(input.now)
        return BonusKind.entries.map { kind ->
            BonusEvaluation(kind, ranges.map { week -> evaluate(kind, week, input) })
        }
    }

    fun evaluate(kind: BonusKind, week: BonusWeekRange, input: EvaluationInput): BonusWeekResult {
        if (week.start > input.now) {
            return BonusWeekResult(week, BonusWeekStatus.UPCOMING, "Aún no inicia")
        }

        val isRunning = input.now in week

        return when (kind) {
            BonusKind.PUNCTUALITY -> {
                val records = input.history.filter { it.startedAt in week }
                val pending = records.sumOf { it.pendingLateMinutes }
                val expected = expectedWorkDays(input.driver, week, input.now)
                val absences = (expected - records.size).coerceAtLeast(0)

                when {
                    absences > 0 -> BonusWeekResult(
                        week,
                        BonusWeekStatus.LOST,
                        if (absences == 1) "1 falta registrada" else "$absences faltas registradas",
                    )

                    pending > 0 -> BonusWeekResult(
                        week,
                        BonusWeekStatus.LOST,
                        "Adeudo ${Fmt.lateText(pending)} sin pagar",
                    )

                    else -> {
                        val lateTotal = records.sumOf { it.lateMinutes }
                        BonusWeekResult(
                            week,
                            if (isRunning) BonusWeekStatus.IN_PROGRESS else BonusWeekStatus.ACHIEVED,
                            if (lateTotal > 0) "Atraso pagado ${Fmt.lateText(lateTotal)}" else "Sin atrasos",
                        )
                    }
                }
            }

            BonusKind.BILLING -> {
                val earned = input.incomes.filter { it.date in week }.sumOf { it.amountMxn }
                val target = input.goals.weeklyMxn
                val detail = "${Fmt.mxn(earned)} de ${Fmt.mxn(target)}"
                if (earned >= target) {
                    BonusWeekResult(week, BonusWeekStatus.ACHIEVED, detail)
                } else {
                    BonusWeekResult(
                        week,
                        if (isRunning) BonusWeekStatus.IN_PROGRESS else BonusWeekStatus.LOST,
                        detail,
                    )
                }
            }

            BonusKind.CARE -> {
                val report = input.reports.firstOrNull { it.createdAt in week }
                if (report != null) {
                    BonusWeekResult(week, BonusWeekStatus.LOST, report.kind.label)
                } else {
                    BonusWeekResult(
                        week,
                        if (isRunning) BonusWeekStatus.IN_PROGRESS else BonusWeekStatus.ACHIEVED,
                        "Sin reportes del supervisor",
                    )
                }
            }

            // Mocked positive until the Uber quality API is available.
            BonusKind.SERVICE -> BonusWeekResult(
                week,
                if (isRunning) BonusWeekStatus.IN_PROGRESS else BonusWeekStatus.ACHIEVED,
                "Calificación ${Fmt.rating(MOCK_QUALITY_SCORE)} · API Uber",
            )
        }
    }

    /** A weekday driver recovers on the weekend and the other way around. */
    fun recoveryGroup(driver: Driver): ShiftGroup =
        if (driver.group == ShiftGroup.WEEKDAY) ShiftGroup.WEEKEND else ShiftGroup.WEEKDAY

    fun recoveryDaysLabel(driver: Driver): String =
        if (driver.group == ShiftGroup.WEEKDAY) "Sábado y domingo" else "Lunes a viernes"

    fun isRecoveryDay(driver: Driver, date: Long): Boolean =
        ShiftRules.group(date) == recoveryGroup(driver)

    /** Bookable when it belongs to the opposite group and has not happened yet. */
    fun canBook(driver: Driver, date: Long, now: Long): Boolean {
        if (!isRecoveryDay(driver, date)) return false
        return date.startOfDay() >= now.startOfDay()
    }
}
