import Foundation
import Observation

/// Single source of truth for the driver session, the active shift and every log.
/// Persists to `UserDefaults` so a reopened app keeps the shift running.
@Observable
final class FleetStore {
    // MARK: - Persisted shape

    nonisolated private struct PersistedState: Codable, Sendable {
        var session: StaffSession?
        /// Account linked to this device; only it can unlock with Face ID.
        var enrolledAccountId: String?
        var vehicles: [Vehicle]
        var activeShift: ActiveShift?
        var history: [ShiftRecord]
        var incomes: [IncomeEntry]
        var incidents: [Incident]
        var notices: [Notice]
        var credit: CreditAccount?
        var clockOffsetMinutes: Int
        var supervisorReports: [SupervisorReport]
        var recoveryBookings: [RecoveryBooking]
        var notifiedBonusWeeks: [String]
    }

    private static let storageKey = "turnoev.state.v4"

    /// Average fleet speed used to estimate distance until real GPS/telemetry lands.
    private static let simulatedKmPerMinute = 0.32

    // MARK: - State

    /// Driver profile of the open session. It follows the active environment: seeded in
    /// production, created by the laboratory in test mode.
    var driver: Driver = MockData.driver

    /// Active session. Its role is the single gate that opens an interface.
    var session: StaffSession?
    /// Credential enrolled on this device for biometric unlock.
    var enrolledAccountId: String?
    var vehicles: [Vehicle] = []
    var activeShift: ActiveShift?
    var history: [ShiftRecord] = []
    var incomes: [IncomeEntry] = []
    var incidents: [Incident] = []
    var notices: [Notice] = []
    /// Used-unit credit contract; `nil` while the driver has not signed one.
    var credit: CreditAccount?
    /// Reports generated by the station supervisor; they break the vehicle-care bonus.
    var supervisorReports: [SupervisorReport] = []
    /// Days reserved in the bonus recovery program.
    var recoveryBookings: [RecoveryBooking] = []
    /// Bonus weeks already announced, so the popup is shown only once.
    var notifiedBonusWeeks: [String] = []
    /// Unit the station tied to this driver. Written by the supervisor, read here.
    var unitAssignment: VehicleAssignment?
    /// Demo-only offset applied to the device clock so every shift rule can be reviewed.
    var clockOffsetMinutes: Int = 0
    /// Set right after an explicit sign out: the access screen then waits for a
    /// credential choice instead of unlocking the same role again by itself.
    var awaitsCredentialChoice: Bool = false

    init() {
        let seedDate = Date()
        let seedHistory = MockData.shiftHistory(driver: MockData.driver, now: seedDate)

        if let restored = Self.restore() {
            apply(restored)
        } else {
            vehicles = MockData.syncOdometers(vehicles: MockData.vehicles, history: seedHistory)
            history = seedHistory
            incomes = MockData.incomeHistory(driver: MockData.driver, history: seedHistory)
            incidents = MockData.incidents(driver: MockData.driver, now: seedDate)
            notices = MockData.notices(now: seedDate)
            supervisorReports = MockData.supervisorReports(now: seedDate)
        }
        // A restored session carries only an account id: the driver profile is not
        // persisted, so it has to be resolved again from the credential. Without this the
        // app relaunches on `MockData.driver`, which is session-blind — in test mode that
        // is the laboratory's first driver, or `drv-none`, never the signed-in one.
        adoptSessionDriver()
        reloadAssignment()
    }

    /// Aligns `driver` with the credential of the open session.
    ///
    /// Only ever runs for a driver session, and only overwrites when the environment can
    /// actually answer for that credential; anything else leaves the current profile
    /// untouched.
    private func adoptSessionDriver() {
        guard let account = currentAccount, account.role == .driver else { return }
        guard let profile = MockData.driver(for: account) else { return }
        driver = profile
    }

    // MARK: - Unit assignment

    /// Pulls the assignment the supervisor wrote.
    ///
    /// What the station wrote always wins, unconditionally — this never overrides, edits
    /// or discards a stored record, not even one pointing at a unit the current
    /// environment does not hold. Tying a unit to a driver is the supervisor's act and
    /// this method never performs it, with the single scoped exception below.
    ///
    /// Without a stored record the driver has **no** unit: `unitAssignment` stays `nil`
    /// and the start screen says so. That is the correct operational state, and it is what
    /// every driver gets.
    func reloadAssignment() {
        if let stored = AssignmentBook.assignment(driverId: driver.id) {
            unitAssignment = stored
            return
        }
        guard let seeded = demoTitularUnit() else {
            unitAssignment = nil
            return
        }
        let assignment = AssignmentBook.make(
            stationId: driver.stationId,
            driverId: driver.id,
            driverName: driver.name,
            vehicleId: seeded.id,
            vehicleNumber: seeded.internalNumber,
            kind: .titular,
            note: "Asignación inicial del perfil de demostración.",
            assignedBy: "Supervisión de estación",
            now: now,
            previous: nil
        )
        AssignmentBook.upsert(assignment)
        unitAssignment = assignment
    }

    /// TEV-014 for Carlos Méndez Rivas, and for nobody else.
    ///
    /// One hardcoded pair, so the demonstration profile is navigable end to end without a
    /// supervisor session. This is **not** a general rule and must not become one: outside
    /// this exact driver and this exact unit, an unassigned driver stays unassigned, which
    /// is what the operational flow requires.
    ///
    /// The guards, in order: only the seeded demo driver — which is what confines this to
    /// one person in either environment — and only his titular unit, and only while that
    /// unit is still one of **his own** existing authorizations; the pair is checked
    /// against `authorizedVehicleIds`, never added to it.
    ///
    /// There is deliberately no environment guard. The demo credential now resolves to
    /// Carlos in test mode too, and a profile that opens without a unit there is precisely
    /// the failure this pairing exists to prevent. A laboratory driver is unaffected: he
    /// fails the identity guard on the first line.
    ///
    /// The remaining checks mirror the non-temporal blocking rules of
    /// `ShiftRules.validateUnit`: same station, free, operational, not held by another
    /// driver in the station's book. Seeding a unit that fails one of them would plant a
    /// permanent blocker on the start screen — worse than no unit. The temporal rule is
    /// deliberately excluded: the assignment exists at every hour, and the start window is
    /// judged when the driver actually tries to start.
    private func demoTitularUnit() -> Vehicle? {
        guard driver.id == MockData.seededDriver.id else { return nil }

        let unitId = MockData.seededTitularVehicleId
        guard driver.authorizedVehicleIds.contains(unitId) else { return nil }
        guard let vehicle = vehicles.first(where: { $0.id == unitId }) else { return nil }
        guard vehicle.stationId == driver.stationId else { return nil }
        guard vehicle.status == .available else { return nil }
        guard vehicle.occupiedBy == nil || vehicle.occupiedBy == driver.id else { return nil }
        // Not tied to another driver in the station's book.
        if let holder = AssignmentBook.holder(vehicleId: unitId), holder.driverId != driver.id {
            return nil
        }
        return vehicle
    }

    /// The unit the driver must take today: the substitute while it lasts, the titular one otherwise.
    var assignedVehicle: Vehicle? {
        guard let unitAssignment else { return nil }
        return vehicles.first { $0.id == unitAssignment.vehicleId }
    }

    var hasAssignedUnit: Bool { assignedVehicle != nil }

    /// Unit shown on the home screen: the one being driven, or the fixed one.
    var displayVehicle: Vehicle? { activeVehicle ?? assignedVehicle }

    // MARK: - Session scope

    var isAuthenticated: Bool { session != nil }

    var currentAccount: StaffAccount? { StaffDirectory.account(id: session?.accountId) }

    var currentRole: StaffRole? { session?.role }

    var currentStation: Station? { StaffDirectory.station(id: session?.stationId) }

    /// Account allowed to unlock this device with Face ID, if any.
    var enrolledAccount: StaffAccount? { StaffDirectory.account(id: enrolledAccountId) }

    /// Interfaces are opened by role only: a driver can never render a supervisor screen.
    func hasAccess(to role: StaffRole) -> Bool { session?.role == role }

    /// The driver profile is exposed only inside a driver session.
    var driverProfile: Driver? {
        guard let account = currentAccount, account.role == .driver, account.driverId == driver.id else { return nil }
        return driver
    }

    // MARK: - Derived values

    /// Time the app obeys. It never comes from the phone: in production it is real time
    /// and in a simulation it is the logical time of the test environment, shared by every
    /// role and every device.
    ///
    /// **A pure read.** It answers what hour it is and registers no SwiftUI dependency.
    ///
    /// It used to read `ClockSignal.generation` first. That was load-bearing at the time and
    /// is deliberately gone now: one indiscriminate counter meant any adopted clock state
    /// invalidated every reader of `store.now` at once, across all seven roles — and worse,
    /// screens inherited temporal correctness by accident, through a side effect none of
    /// them named. Views that genuinely follow the clock now say so, one at a time, with
    /// `TimeScope` or `ClockAnchor`.
    ///
    /// Use this for **action time**: the instant a decision is taken, a form is preloaded, a
    /// snapshot is rebuilt or a seed key is computed. Never to make something on screen move
    /// by itself — nothing observes this any more, and nothing should.
    var now: Date {
        AppClock.now()
    }

    var activeVehicle: Vehicle? {
        guard let shift = activeShift else { return nil }
        return vehicles.first { $0.id == shift.vehicleId }
    }

    var unreadNoticeCount: Int { notices.filter { !$0.read }.count }

    var hasCredit: Bool { credit != nil }

    /// Transparent contract metrics for the credit panel.
    var creditMetrics: CreditMetrics? {
        guard let credit else { return nil }
        return CreditProgram.metrics(for: credit, now: now)
    }

    var goals: ShiftRules.Goals { ShiftRules.goals(for: driver.group) }

    func elapsedSeconds(at date: Date) -> Int {
        guard let shift = activeShift else { return 0 }
        return max(0, Int(date.timeIntervalSince(shift.startedAt)))
    }

    func estimatedKmDriven(at date: Date) -> Int {
        Int((Double(elapsedSeconds(at: date)) / 60 * Self.simulatedKmPerMinute).rounded())
    }

    var capturedPhotoCount: Int { activeShift?.photos.count ?? 0 }

    /// The start of shift only needs the odometer and the battery readings.
    var isInspectionComplete: Bool {
        guard let shift = activeShift else { return false }
        return InspectionSlot.driverSlots.allSatisfy { shift.photos[$0.rawValue] != nil }
    }

    /// Monday → Sunday late-minute log, the "bitácora" shown in Historial.
    struct LateDay: Identifiable, Sendable {
        let date: Date
        let label: String
        let minutes: Int
        let paidBackMinutes: Int
        let hasShift: Bool

        var id: Date { date }
        var pendingMinutes: Int { max(0, minutes - paidBackMinutes) }
    }

    func weeklyLateBreakdown(reference: Date) -> [LateDay] {
        let calendar = ShiftRules.calendar
        let start = ShiftRules.weekStart(for: reference)
        return (0..<7).compactMap { offset in
            guard let day = calendar.date(byAdding: .day, value: offset, to: start) else { return nil }
            let record = history.first { ShiftRules.isSameDay($0.startedAt, day) }
            return LateDay(
                date: day,
                label: Fmt.dayShort(day),
                minutes: record?.lateMinutes ?? 0,
                paidBackMinutes: record?.paidBackMinutes ?? 0,
                hasShift: record != nil
            )
        }
    }

    func weeklyLateDebt(reference: Date) -> Int {
        weeklyLateBreakdown(reference: reference).reduce(0) { $0 + $1.pendingMinutes }
    }

    func earnedToday(reference: Date) -> Int {
        let fromIncomes = incomes
            .filter { ShiftRules.isSameDay($0.date, reference) }
            .reduce(0) { $0 + $1.amountMxn }
        let fromClosedShifts = history
            .filter { ShiftRules.isSameDay($0.startedAt, reference) }
            .reduce(0) { $0 + $1.earningsMxn }
        return max(fromIncomes, fromClosedShifts, activeShift?.earningsMxn ?? 0)
    }

    func tripsToday(reference: Date) -> Int {
        let fromIncomes = incomes
            .filter { ShiftRules.isSameDay($0.date, reference) }
            .reduce(0) { $0 + $1.trips }
        return max(fromIncomes, activeShift?.trips ?? 0)
    }

    func earnedThisWeek(reference: Date) -> Int {
        incomes
            .filter { ShiftRules.isInSameWeek($0.date, as: reference) }
            .reduce(0) { $0 + $1.amountMxn }
    }

    struct DayEarnings: Identifiable, Sendable {
        let label: String
        let amount: Int
        let isToday: Bool
        let date: Date

        var id: Date { date }
    }

    func weeklyEarningsByDay(reference: Date) -> [DayEarnings] {
        let calendar = ShiftRules.calendar
        let start = ShiftRules.weekStart(for: reference)
        return (0..<7).compactMap { offset in
            guard let day = calendar.date(byAdding: .day, value: offset, to: start) else { return nil }
            let amount = incomes
                .filter { ShiftRules.isSameDay($0.date, day) }
                .reduce(0) { $0 + $1.amountMxn }
            return DayEarnings(
                label: Fmt.dayShort(day),
                amount: amount,
                isToday: ShiftRules.isSameDay(day, reference),
                date: day
            )
        }
    }

    // MARK: - Session

    /// Opens the session for an already authenticated account and links the device
    /// so future biometric unlocks resolve to this same credential.
    func signIn(account: StaffAccount, method: SignInMethod) {
        if let profile = MockData.driver(for: account) {
            driver = profile
        } else if LabRuntime.isTest, account.role == .driver {
            driver = MockData.driver
        }
        defer { reloadAssignment() }
        session = StaffSession(
            accountId: account.id,
            role: account.role,
            stationId: account.stationId,
            method: method,
            startedAt: Date()
        )
        enrolledAccountId = account.id
        awaitsCredentialChoice = false
        persist()
    }

    /// Closes the session and returns to the access screen. The automatic scan is held
    /// back so another role can be identified instead of re-entering the same one.
    func signOut() {
        session = nil
        awaitsCredentialChoice = true
        persist()
    }

    /// Removes the biometric link so the next access requires full credentials.
    func forgetDevice() {
        enrolledAccountId = nil
        session = nil
        awaitsCredentialChoice = true
        persist()
    }

    /// Rebuilds the operational state from the active environment. Called whenever the
    /// laboratory changes the world so every interface reflects it immediately.
    func adoptEnvironment() {
        defer { reloadAssignment() }
        // Same reasoning as in `init`: the session outlives the environment switch, so the
        // profile is resolved from the credential and only falls back to the
        // environment's default driver when the credential has none.
        driver = MockData.driver
        adoptSessionDriver()
        let source = MockData.vehicles
        let activeVehicleId = activeShift?.vehicleId

        vehicles = source.map { incoming in
            guard let kept = vehicles.first(where: { $0.id == incoming.id }) else { return incoming }
            // A unit inside a running shift keeps its live readings; every other unit
            // follows the environment, so lab edits land immediately.
            guard kept.id != activeVehicleId, LabRuntime.isTest else { return kept }
            return incoming
        }

        if let shift = activeShift, !vehicles.contains(where: { $0.id == shift.vehicleId }) {
            activeShift = nil
        }
        persist()
    }

    /// Wipes every operational record of the driver interface, leaving it at zero.
    func clearOperationalData() {
        vehicles = MockData.vehicles
        activeShift = nil
        history = []
        incomes = []
        incidents = []
        notices = []
        credit = nil
        supervisorReports = []
        recoveryBookings = []
        notifiedBonusWeeks = []
        clockOffsetMinutes = 0
        driver = MockData.driver
        AssignmentBook.clear()
        unitAssignment = nil
        persist()
    }

    func setClockOffset(minutes: Int) {
        clockOffsetMinutes = minutes
        persist()
    }

    /// Keeps the persisted offset in step with the logical hour.
    ///
    /// This is **not** the invalidation mechanism any more. An integer number of minutes
    /// cannot express a second, a speed, a pause or a new revision landing on the same
    /// minute, so driving the interface from it left every one of those changes invisible.
    /// `ClockSignal` does the invalidating; this only maintains stored state.
    func syncSimulationClock() {
        let offset = AppClock.offsetMinutes()
        guard clockOffsetMinutes != offset else { return }
        clockOffsetMinutes = offset
        persist()
    }

    // MARK: - Start window

    var windowState: ShiftRules.WindowState { ShiftRules.windowState(driver: driver, now: now) }

    /// The block the driver belongs to is already over: a running shift has to be closed.
    var isWorkdayClosed: Bool { ShiftRules.isPastClose(slot: driver.slot, now: now) }

    var startWindow: (opensAt: Date, closesAt: Date) { ShiftRules.startWindow(slot: driver.slot, now: now) }

    /// Sends the blocking reason to the station so the supervisor can act on it.
    func notifySupervisor(reason: String) {
        pushNotice(
            kind: .station,
            title: "Reporte enviado a supervisión",
            body: reason
        )
    }

    func resetDemoData() {
        guard !LabRuntime.isTest else {
            clearOperationalData()
            return
        }
        let seedDate = Date()
        let seedHistory = MockData.shiftHistory(driver: driver, now: seedDate)
        vehicles = MockData.syncOdometers(vehicles: MockData.vehicles, history: seedHistory)
        history = seedHistory
        incomes = MockData.incomeHistory(driver: driver, history: seedHistory)
        incidents = MockData.incidents(driver: driver, now: seedDate)
        notices = MockData.notices(now: seedDate)
        credit = MockData.credit(now: seedDate)
        supervisorReports = MockData.supervisorReports(now: seedDate)
        recoveryBookings = []
        notifiedBonusWeeks = []
        activeShift = nil
        clockOffsetMinutes = 0
        CashDepositLedger.clear()
        CashChargeLedger.clear()
        persist()
    }

    // MARK: - Bonuses

    private func bonusInput(reference: Date) -> BonusRules.EvaluationInput {
        BonusRules.EvaluationInput(
            driver: driver,
            goals: goals,
            history: history,
            incomes: incomes,
            reports: supervisorReports,
            schedule: NationalBonusBoard.current,
            now: reference
        )
    }

    func bonusEvaluations(reference: Date) -> [BonusEvaluation] {
        BonusRules.evaluateAll(bonusInput(reference: reference))
    }

    /// Money still collectable at month end with the current weekly evaluation.
    func bonusPayableMxn(reference: Date) -> Int {
        bonusEvaluations(reference: reference).reduce(0) { $0 + $1.payableMxn }
    }

    /// Everything the month can pay with the amounts the national administration has
    /// in force. Stations cannot alter this number.
    func bonusTotalMxn() -> Int {
        NationalBonusBoard.current.ceilingMxn
    }

    /// Raises the popup for the first closed week that broke a bonus, once only.
    @discardableResult
    func raiseBonusAlert(reference: Date) -> BonusAlert? {
        let evaluations = bonusEvaluations(reference: reference)
        for evaluation in evaluations {
            for result in evaluation.weeks where result.status == .lost {
                let id = "\(evaluation.kind.rawValue)-\(Fmt.monthKey(reference))-\(result.week.index)"
                guard !notifiedBonusWeeks.contains(id) else { continue }
                let message = "¡\(Fmt.firstName(driver.name)) has perdido el bono de \(evaluation.kind.shortName)! Agenda hoy tu lugar en el programa de recuperación de bonos"
                notifiedBonusWeeks.append(id)
                pushNotice(
                    kind: .reminder,
                    title: message,
                    body: "Semana \(result.week.index) (\(result.week.rangeLabel)): \(result.detail)."
                )
                return BonusAlert(id: id, kind: evaluation.kind, weekIndex: result.week.index, message: message)
            }
        }
        return nil
    }

    // MARK: - Recovery program

    func recoveryBooking(on day: Date) -> RecoveryBooking? {
        recoveryBookings.first { ShiftRules.isSameDay($0.date, day) }
    }

    var upcomingRecoveryBookings: [RecoveryBooking] {
        recoveryBookings.sorted { $0.date < $1.date }
    }

    @discardableResult
    func bookRecovery(date: Date, slot: ShiftSlot, bonus: BonusKind) -> Bool {
        guard BonusRules.canBook(driver: driver, date: date, now: now) else { return false }
        guard recoveryBooking(on: date) == nil else { return false }

        let booking = RecoveryBooking(
            id: "rec-\(UUID().uuidString.prefix(8))",
            date: ShiftRules.calendar.startOfDay(for: date),
            slot: slot,
            bonus: bonus,
            createdAt: now
        )
        recoveryBookings.append(booking)
        pushNotice(
            kind: .station,
            title: "Reserva confirmada en recuperación de bonos",
            body: "\(Fmt.dateShort(booking.date).capitalized) · turno \(slot.label.lowercased()) \(slot.rangeLabel). Recuperas el bono de \(bonus.shortName)."
        )
        return true
    }

    func cancelRecovery(id: String) {
        recoveryBookings.removeAll { $0.id == id }
        persist()
    }

    // MARK: - Shift lifecycle

    func validateAssignment(vehicle: Vehicle, odometerKm: Int, batteryPct: Int) -> [AssignmentIssue] {
        ShiftRules.validateAssignment(
            driver: driver,
            vehicle: vehicle,
            now: now,
            odometerKm: odometerKm,
            batteryPct: batteryPct
        )
    }

    /// Step 1 of the start flow: sticker read against the assigned unit.
    func validateScannedUnit(vehicle: Vehicle) -> [AssignmentIssue] {
        ShiftRules.validateUnit(
            driver: driver,
            vehicle: vehicle,
            assignedVehicleId: unitAssignment?.vehicleId,
            now: now
        )
    }

    /// Step 2: photographed odometer, ±5 km against the registered reading.
    func validateOdometerReading(vehicle: Vehicle, reading: Int) -> AssignmentIssue? {
        ShiftRules.validateOdometer(vehicle: vehicle, reading: reading)
    }

    /// Step 3: photographed charge against the fleet minimum.
    func validateBatteryReading(_ reading: Int) -> AssignmentIssue? {
        ShiftRules.validateBattery(reading: reading)
    }

    /// Closes the three-step flow: opens the shift and files the captured evidence.
    @discardableResult
    func startShift(
        vehicle: Vehicle,
        odometerKm: Int,
        batteryPct: Int,
        odometerPhoto: Data?,
        batteryPhoto: Data?
    ) -> ActiveShift {
        let shift = assign(vehicle: vehicle, odometerKm: odometerKm, batteryPct: batteryPct)
        if let odometerPhoto { saveInspectionPhoto(slot: .odometer, data: odometerPhoto) }
        if let batteryPhoto { saveInspectionPhoto(slot: .battery, data: batteryPhoto) }
        return activeShift ?? shift
    }

    @discardableResult
    func assign(vehicle: Vehicle, odometerKm: Int, batteryPct: Int) -> ActiveShift {
        let startedAt = now
        let scheduled = ShiftRules.scheduledStart(slot: driver.slot, on: startedAt)
        let shift = ActiveShift(
            id: "shift-\(UUID().uuidString.prefix(8))",
            driverId: driver.id,
            vehicleId: vehicle.id,
            group: ShiftRules.group(for: startedAt),
            slot: driver.slot,
            scheduledStartAt: scheduled,
            startedAt: startedAt,
            lateMinutes: ShiftRules.lateMinutes(scheduled: scheduled, actual: startedAt),
            startOdometerKm: odometerKm,
            startBatteryPct: batteryPct,
            photos: [:],
            trips: 0,
            earningsMxn: 0
        )

        activeShift = shift
        if let index = vehicles.firstIndex(where: { $0.id == vehicle.id }) {
            vehicles[index].status = .occupied
            vehicles[index].occupiedBy = driver.id
            vehicles[index].odometerKm = odometerKm
            vehicles[index].batteryPct = batteryPct
        }

        if shift.lateMinutes > 0 {
            pushNotice(
                kind: .reminder,
                title: "Inicio de turno con atraso",
                body: "Iniciaste \(shift.lateMinutes) minutos después de la hora programada. Se registró en tu bitácora."
            )
        }

        persist()
        return shift
    }

    func saveInspectionPhoto(slot: InspectionSlot, data: Data) {
        guard var shift = activeShift else { return }
        shift.photos[slot.rawValue] = data
        activeShift = shift
        persist()
    }

    func registerIncome(amountMxn: Int, trips: Int, platform: IncomePlatform, evidence: Data?, note: String? = nil) {
        let entry = IncomeEntry(
            id: "inc-\(UUID().uuidString.prefix(8))",
            driverId: driver.id,
            shiftId: activeShift?.id,
            date: now,
            amountMxn: amountMxn,
            trips: trips,
            platform: platform,
            evidence: evidence,
            note: note
        )
        incomes.insert(entry, at: 0)

        if var shift = activeShift {
            shift.earningsMxn += amountMxn
            shift.trips += trips
            activeShift = shift
        }
        persist()
    }

    /// The account direction publishes for cash that could not be charged by card.
    var cashDepositAccount: CashDepositAccount { NationalCashBoard.current }

    /// Cash trips the platform reported and that are still in the driver's hands.
    var openCashCharges: [CashCharge] {
        CashChargeLedger.open(driverId: driver.id)
    }

    /// Simulates the platform reporting a trip settled in cash during the shift.
    @discardableResult
    func syncCashChargeFromPlatform(amountMxn: Int) -> CashCharge {
        let charge = CashChargeLedger.make(
            driverId: driver.id,
            stationId: driver.stationId,
            amountMxn: amountMxn,
            now: now
        )
        CashChargeLedger.add(charge)
        pushNotice(
            kind: .station,
            title: "Viaje cobrado en efectivo",
            body: "\(charge.tripReference) por \(Fmt.mxn(amountMxn)). Deposítalo hoy antes de las 23:59:59 o se descontará de tus ingresos de la semana."
        )
        return charge
    }

    /// Closes every cash charge whose day already ended without a deposit. From here the
    /// amount stops being a pending deposit and becomes a discount on the week, visible
    /// in the wallet as "Cobro de viaje en efectivo".
    @discardableResult
    func chargeBackExpiredCashCharges() -> [CashCharge] {
        let expired = openCashCharges.filter { now > CashChargeRules.deadline(for: $0) }
        guard !expired.isEmpty else { return [] }

        for charge in expired {
            CashChargeLedger.markChargedBack(id: charge.id, at: now)
            pushNotice(
                kind: .credit,
                title: "\(CashChargeRules.recoveryConcept) · \(Fmt.mxn(charge.amountMxn))",
                body: "El viaje \(charge.tripReference) del \(Fmt.dateShort(charge.generatedAt)) no se depositó el mismo día. El monto se descuenta de tus ingresos al cierre de la semana."
            )
        }
        return expired
    }

    /// Files a cash deposit: the income enters the day, the slip stays attached and the
    /// manager of the station is notified in the same movement. Cash is not an authorized
    /// way to charge, so every peso received in hand has to leave a trace.
    @discardableResult
    func registerCashDeposit(
        charge: CashCharge,
        declaredMxn: Int,
        detectedMxn: Int?,
        match: DepositMatch,
        accountMatch: DepositMatch,
        detectedAccount: String?,
        slip: Data?
    ) -> CashDeposit {
        let account = cashDepositAccount
        let deposit = CashDeposit(
            id: "dep-\(UUID().uuidString.prefix(8))",
            stationId: driver.stationId,
            driverId: driver.id,
            driverName: driver.name,
            vehicleNumber: displayVehicle?.internalNumber ?? "Sin unidad",
            declaredMxn: declaredMxn,
            detectedMxn: detectedMxn,
            match: match,
            accountMatch: accountMatch,
            detectedAccount: detectedAccount,
            bank: account.bank,
            clabe: account.clabe,
            createdAt: now,
            slip: slip,
            acknowledgedAt: nil
        )
        CashDepositLedger.record(deposit)
        CashChargeLedger.markDeposited(id: charge.id, at: now)

        registerIncome(
            amountMxn: declaredMxn,
            trips: 0,
            platform: .cash,
            evidence: slip,
            note: "\(charge.tripReference) · depósito en \(account.bank)"
        )

        pushNotice(
            kind: .station,
            title: "Depósito en efectivo notificado a gerencia",
            body: "\(Fmt.mxn(declaredMxn)) del viaje \(charge.tripReference) depositados en \(account.bank). El gerente de \(driver.station) recibió el comprobante."
        )
        return deposit
    }

    func reportIncident(kind: IncidentKind, description: String, photos: [Data]) {
        let vehicle = activeVehicle ?? vehicles.first
        let incident = Incident(
            id: "inci-\(UUID().uuidString.prefix(8))",
            driverId: driver.id,
            vehicleId: vehicle?.id ?? "—",
            vehicleInternalNumber: vehicle?.internalNumber ?? "—",
            kind: kind,
            createdAt: now,
            description: description,
            photos: photos,
            status: .open
        )
        incidents.insert(incident, at: 0)
        pushNotice(
            kind: .station,
            title: "Incidencia enviada a la estación",
            body: "Tu reporte de \(kind.label.lowercased()) quedó en revisión."
        )
        persist()
    }

    func finishShift(endOdometerKm: Int, endBatteryPct: Int, photo: Data?) -> ShiftSummary {
        guard let shift = activeShift else {
            return ShiftSummary(
                kmDriven: 0,
                durationMinutes: 0,
                earningsMxn: 0,
                trips: 0,
                dailyGoalMxn: goals.dailyMxn,
                missingMxn: goals.dailyMxn,
                missingTrips: goals.tripsPerDay,
                lateMinutes: 0
            )
        }

        let endedAt = now
        let record = ShiftRecord(
            id: shift.id,
            driverId: shift.driverId,
            vehicleId: shift.vehicleId,
            vehicleInternalNumber: activeVehicle?.internalNumber ?? "—",
            group: shift.group,
            slot: shift.slot,
            scheduledStartAt: shift.scheduledStartAt,
            startedAt: shift.startedAt,
            endedAt: endedAt,
            lateMinutes: shift.lateMinutes,
            paidBackMinutes: 0,
            startOdometerKm: shift.startOdometerKm,
            endOdometerKm: endOdometerKm,
            startBatteryPct: shift.startBatteryPct,
            endBatteryPct: endBatteryPct,
            trips: shift.trips,
            earningsMxn: shift.earningsMxn
        )

        history.insert(record, at: 0)
        if let index = vehicles.firstIndex(where: { $0.id == shift.vehicleId }) {
            vehicles[index].status = .available
            vehicles[index].occupiedBy = nil
            vehicles[index].odometerKm = endOdometerKm
            vehicles[index].batteryPct = endBatteryPct
        }
        if photo != nil {
            // Final odometer evidence is archived with the closed shift record.
            pushNotice(
                kind: .station,
                title: "Turno cerrado",
                body: "Entregaste \(record.vehicleInternalNumber) con \(Fmt.km(endOdometerKm)). Duración \(Fmt.durationText(record.durationMinutes))."
            )
        }
        activeShift = nil
        persist()

        return ShiftSummary(
            kmDriven: record.kmDriven,
            durationMinutes: record.durationMinutes,
            earningsMxn: record.earningsMxn,
            trips: record.trips,
            dailyGoalMxn: goals.dailyMxn,
            missingMxn: max(0, goals.dailyMxn - record.earningsMxn),
            missingTrips: max(0, goals.tripsPerDay - record.trips),
            lateMinutes: record.lateMinutes
        )
    }

    /// Applies paid-back minutes to the oldest pending late day of the current week.
    @discardableResult
    func payLateTime(minutes: Int) -> Int {
        var remaining = minutes
        var applied = 0
        let weekDays = weeklyLateBreakdown(reference: now).filter { $0.pendingMinutes > 0 }
        let pendingDates = weekDays.map(\.date)

        for index in history.indices where remaining > 0 {
            let record = history[index]
            guard pendingDates.contains(where: { ShiftRules.isSameDay($0, record.startedAt) }) else { continue }
            let pending = record.pendingLateMinutes
            guard pending > 0 else { continue }
            let pay = min(pending, remaining)
            history[index].paidBackMinutes += pay
            remaining -= pay
            applied += pay
        }

        if applied > 0 { persist() }
        return applied
    }

    // MARK: - Credit

    /// Signs a new contract: no down payment, immediate approval, first instalment in a week.
    func requestCredit() {
        guard credit == nil else { return }
        let reference = now
        let unit = vehicles.first { driver.authorizedVehicleIds.contains($0.id) }?.internalNumber ?? "por asignar"
        credit = CreditProgram.newAccount(now: reference, vehicleInternalNumber: unit)
        pushNotice(
            kind: .credit,
            title: "Crédito aprobado",
            body: "Tu contrato del \(CreditProgram.vehicleModel) quedó firmado. El primer abono semanal se descuenta en 7 días."
        )
    }

    /// Loads the seeded mid-term contract so every metric of the panel can be reviewed.
    func loadCreditDemoProgress() {
        credit = MockData.credit(now: now)
        persist()
    }

    /// Returns the driver to the promotional banner state.
    func cancelCredit() {
        credit = nil
        persist()
    }

    // MARK: - Notices

    func markNoticeRead(id: String) {
        guard let index = notices.firstIndex(where: { $0.id == id }) else { return }
        notices[index].read = true
        persist()
    }

    func markAllNoticesRead() {
        notices = notices.map { notice in
            var updated = notice
            updated.read = true
            return updated
        }
        persist()
    }

    func pushNotice(kind: NoticeKind, title: String, body: String) {
        notices.insert(
            Notice(
                id: "not-\(UUID().uuidString.prefix(8))",
                kind: kind,
                title: title,
                body: body,
                createdAt: now,
                read: false
            ),
            at: 0
        )
        persist()
    }

    // MARK: - Persistence

    private func apply(_ state: PersistedState) {
        session = state.session
        enrolledAccountId = state.enrolledAccountId
        vehicles = state.vehicles
        activeShift = state.activeShift
        history = state.history
        incomes = state.incomes
        incidents = state.incidents
        notices = state.notices
        credit = state.credit
        clockOffsetMinutes = state.clockOffsetMinutes
        supervisorReports = state.supervisorReports
        recoveryBookings = state.recoveryBookings
        notifiedBonusWeeks = state.notifiedBonusWeeks
    }

    private func persist() {
        let state = PersistedState(
            session: session,
            enrolledAccountId: enrolledAccountId,
            vehicles: vehicles,
            activeShift: activeShift,
            history: history,
            incomes: incomes,
            incidents: incidents,
            notices: notices,
            credit: credit,
            clockOffsetMinutes: clockOffsetMinutes,
            supervisorReports: supervisorReports,
            recoveryBookings: recoveryBookings,
            notifiedBonusWeeks: notifiedBonusWeeks
        )
        do {
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .iso8601
            let data = try encoder.encode(state)
            UserDefaults.standard.set(data, forKey: Self.storageKey)
        } catch {
            print("No se pudo guardar el estado local: \(error.localizedDescription)")
        }
    }

    nonisolated private static func restore() -> PersistedState? {
        guard let data = UserDefaults.standard.data(forKey: storageKey) else { return nil }
        do {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            return try decoder.decode(PersistedState.self, from: data)
        } catch {
            print("No se pudo leer el estado local: \(error.localizedDescription)")
            return nil
        }
    }
}
