import Foundation
import Observation

/// Why a proved identity was still not allowed to open a session.
///
/// A driver whose membership is incomplete is a data problem, not a login the app may
/// paper over: nothing here is defaulted, so the session simply does not open and the
/// reason is legible on the access screen.
nonisolated enum SessionOpenError: LocalizedError, Sendable {
    case missingStation
    case missingStationName
    case missingShiftGroup
    case missingShiftSlot

    var errorDescription: String? {
        switch self {
        case .missingStation:
            return "Tu cuenta no tiene estación asignada. Contacta a tu supervisor."
        case .missingStationName:
            return "La estación de tu cuenta no tiene nombre registrado. Contacta a tu supervisor."
        case .missingShiftGroup:
            return "Tu cuenta no tiene grupo de turno asignado. Contacta a tu supervisor."
        case .missingShiftSlot:
            return "Tu cuenta no tiene horario de turno asignado. Contacta a tu supervisor."
        }
    }
}

/// Single source of truth for the driver session, the active shift and every log.
/// Persists to `UserDefaults` so a reopened app keeps the shift running.
@Observable
final class FleetStore {
    // MARK: - Persisted shape

    nonisolated private struct PersistedState: Codable, Sendable {
        var session: StaffSession?
        /// Account linked to this device; only it can unlock with Face ID.
        var enrolledAccountId: String?
        var vehicles: [Vehicle]
        var activeShift: ActiveShift?
        var history: [ShiftRecord]
        var incomes: [IncomeEntry]
        var incidents: [Incident]
        var notices: [Notice]
        var credit: CreditAccount?
        var clockOffsetMinutes: Int
        var supervisorReports: [SupervisorReport]
        var recoveryBookings: [RecoveryBooking]
        var notifiedBonusWeeks: [String]
    }

    /// Storage of the demonstration credentials. Untouched: everything a demo session
    /// ever wrote stays exactly where it was and keeps being read from here.
    private static let demoStorageKey = "turnoev.state.v4"

    /// Storage of one identity proved by the backend, in one environment.
    ///
    /// Derived from `profileId` — never from the email and never from the password — so
    /// the key is stable across renames and carries no credential. One driver per key is
    /// what makes "driver A never reads the state of driver B" a property of the storage
    /// itself instead of a filter someone has to remember to apply.
    ///
    /// The environment is part of the key for the same reason the driver is. A laboratory
    /// experiment run by a proved identity and that identity's real operation are two
    /// different operations, and separating them at the storage layer is what makes
    /// "nothing simulated survives the way back to production" and "nothing real is
    /// deleted on the way into the laboratory" properties of the container instead of
    /// clean-up code someone has to run. The production key is byte-for-byte the one that
    /// already exists: nothing stored needs migrating.
    nonisolated private static func identityStorageKey(profileId: String, environment: LabMode) -> String {
        switch environment {
        case .production: "\(demoStorageKey).\(profileId)"
        case .test: "\(demoStorageKey).lab.\(profileId)"
        }
    }

    /// Key this session uses in a given environment.
    ///
    /// A demonstration session answers the same key in both: it *is* the simulation, and
    /// giving it a second blob would change behaviour that is deliberately frozen.
    private func storageKey(for environment: LabMode) -> String {
        guard let profileId = session?.principal?.profileId else { return Self.demoStorageKey }
        return Self.identityStorageKey(profileId: profileId, environment: environment)
    }

    /// Key the open session reads from and writes to right now.
    private var storageKey: String { storageKey(for: adoptedEnvironment) }

    /// Average fleet speed used to estimate distance until real GPS/telemetry lands.
    private static let simulatedKmPerMinute = 0.32

    // MARK: - State

    /// Driver profile of the open session. It follows the active environment: seeded in
    /// production, created by the laboratory in test mode.
    var driver: Driver = MockData.driver

    /// Active session. Its role is the single gate that opens an interface.
    var session: StaffSession?
    /// Credential enrolled on this device for biometric unlock.
    var enrolledAccountId: String?
    var vehicles: [Vehicle] = []
    var activeShift: ActiveShift?
    var history: [ShiftRecord] = []
    var incomes: [IncomeEntry] = []
    var incidents: [Incident] = []
    var notices: [Notice] = []
    /// Used-unit credit contract; `nil` while the driver has not signed one.
    var credit: CreditAccount?
    /// Reports generated by the station supervisor; they break the vehicle-care bonus.
    var supervisorReports: [SupervisorReport] = []
    /// Days reserved in the bonus recovery program.
    var recoveryBookings: [RecoveryBooking] = []
    /// Bonus weeks already announced, so the popup is shown only once.
    var notifiedBonusWeeks: [String] = []
    /// Unit the station tied to this driver. Written by the supervisor, read here.
    var unitAssignment: VehicleAssignment?
    /// Demo-only offset applied to the device clock so every shift rule can be reviewed.
    var clockOffsetMinutes: Int = 0
    /// Set right after an explicit sign out: the access screen then waits for a
    /// credential choice instead of unlocking the same role again by itself.
    var awaitsCredentialChoice: Bool = false

    /// The one observable source of the execution environment. Read live by every
    /// capability below, so a change is visible to the same session immediately.
    private let environmentSource: RuntimeEnvironment

    /// Where this store persists. Injectable so a test never writes on a real device
    /// state; the app always passes `.standard`.
    private let defaults: UserDefaults

    /// Which environment the state **currently in memory** belongs to.
    ///
    /// Deliberately not a source of truth and never consulted by a capability: it only
    /// answers "which key was this loaded from", so the swap can write the outgoing state
    /// under the right key before reading the incoming one. `environmentSource` is the
    /// truth; this is a bookmark, refreshed by `adoptEnvironment()`.
    private var adoptedEnvironment: LabMode

    init(environment: RuntimeEnvironment = .shared, defaults: UserDefaults = .standard) {
        self.environmentSource = environment
        self.defaults = defaults
        self.adoptedEnvironment = environment.mode
        // The app always opens on the demonstration storage: a backend session is never
        // restored (see `apply`), so this is the only state that can be standing when the
        // access screen appears.
        if let restored = Self.restore(key: Self.demoStorageKey, defaults: defaults) {
            apply(restored)
        } else {
            seedDemoState()
        }
        // A restored session carries only an account id: the driver profile is not
        // persisted, so it has to be resolved again from the credential. Without this the
        // app relaunches on `MockData.driver`, which is session-blind — in test mode that
        // is the laboratory's first driver, or `drv-none`, never the signed-in one.
        adoptSessionDriver()
        // A contract stored before 15B.10 carries no owner. Now that the demonstration
        // profile is resolved, it can be named — see `demoAttributed`.
        credit = Self.demoAttributed(credit, driverId: driver.id)
        reloadAssignment()
    }

    /// Demonstration seeds, unchanged in content.
    ///
    /// Extracted from `init` so that leaving a backend session can rebuild them on a
    /// device that never stored a demonstration state of its own.
    private func seedDemoState() {
        let seedDate = Date()
        let seedHistory = MockData.shiftHistory(driver: MockData.driver, now: seedDate)
        vehicles = MockData.syncOdometers(vehicles: MockData.vehicles, history: seedHistory)
        activeShift = nil
        history = seedHistory
        incomes = MockData.incomeHistory(driver: MockData.driver, history: seedHistory)
        incidents = MockData.incidents(driver: MockData.driver, now: seedDate)
        notices = MockData.notices(now: seedDate)
        credit = nil
        supervisorReports = MockData.supervisorReports(now: seedDate)
        recoveryBookings = []
        notifiedBonusWeeks = []
    }

    /// Aligns `driver` with the credential of the open session.
    ///
    /// Only ever runs for a driver session, and only overwrites when the environment can
    /// actually answer for that credential; anything else leaves the current profile
    /// untouched.
    private func adoptSessionDriver() {
        // A backend session already carries its own driver, built from the principal the
        // server proved. The directory has no entry for that person and must never be
        // asked to supply one.
        guard session?.principal == nil else { return }
        guard let account = currentAccount, account.role == .driver else { return }
        guard let profile = MockData.driver(for: account) else { return }
        driver = profile
    }

    // MARK: - Unit assignment

    /// Pulls the assignment the supervisor wrote.
    ///
    /// What the station wrote always wins, unconditionally — this never overrides, edits
    /// or discards a stored record, not even one pointing at a unit the current
    /// environment does not hold. Tying a unit to a driver is the supervisor's act and
    /// this method never performs it, with the single scoped exception below.
    ///
    /// Without a stored record the driver has **no** unit: `unitAssignment` stays `nil`
    /// and the start screen says so. That is the correct operational state, and it is what
    /// every driver gets.
    func reloadAssignment() {
        let capability = unitAssignmentCapability
        if let adopted = UnitAssignmentRules.resolve(
            stored: AssignmentBook.assignment(driverId: driver.id),
            driverId: driver.id,
            capability: capability
        ) {
            unitAssignment = adopted
            return
        }
        // Seeding is a write into the shared book, so it is the boundary's business too:
        // a proved identity never fabricates its own assignment, not even the demo pair.
        guard capability.allowsLocalSimulation, let seeded = demoTitularUnit() else {
            unitAssignment = nil
            return
        }
        let assignment = AssignmentBook.make(
            stationId: driver.stationId,
            driverId: driver.id,
            driverName: driver.name,
            vehicleId: seeded.id,
            vehicleNumber: seeded.internalNumber,
            kind: .titular,
            note: "Asignación inicial del perfil de demostración.",
            assignedBy: "Supervisión de estación",
            origin: .simulated,
            now: now,
            previous: nil
        )
        AssignmentBook.upsert(assignment)
        unitAssignment = assignment
    }

    /// TEV-014 for Carlos Méndez Rivas, and for nobody else.
    ///
    /// One hardcoded pair, so the demonstration profile is navigable end to end without a
    /// supervisor session. This is **not** a general rule and must not become one: outside
    /// this exact driver and this exact unit, an unassigned driver stays unassigned, which
    /// is what the operational flow requires.
    ///
    /// The guards, in order: only the seeded demo driver — which is what confines this to
    /// one person in either environment — and only his titular unit, and only while that
    /// unit is still one of **his own** existing authorizations; the pair is checked
    /// against `authorizedVehicleIds`, never added to it.
    ///
    /// There is deliberately no environment guard. The demo credential now resolves to
    /// Carlos in test mode too, and a profile that opens without a unit there is precisely
    /// the failure this pairing exists to prevent. A laboratory driver is unaffected: he
    /// fails the identity guard on the first line.
    ///
    /// The remaining checks mirror the non-temporal blocking rules of
    /// `ShiftRules.validateUnit`: same station, free, operational, not held by another
    /// driver in the station's book. Seeding a unit that fails one of them would plant a
    /// permanent blocker on the start screen — worse than no unit. The temporal rule is
    /// deliberately excluded: the assignment exists at every hour, and the start window is
    /// judged when the driver actually tries to start.
    private func demoTitularUnit() -> Vehicle? {
        guard driver.id == MockData.seededDriver.id else { return nil }

        let unitId = MockData.seededTitularVehicleId
        guard driver.authorizedVehicleIds.contains(unitId) else { return nil }
        guard let vehicle = vehicles.first(where: { $0.id == unitId }) else { return nil }
        guard vehicle.stationId == driver.stationId else { return nil }
        guard vehicle.status == .available else { return nil }
        guard vehicle.occupiedBy == nil || vehicle.occupiedBy == driver.id else { return nil }
        // Not tied to another driver in the station's book.
        if let holder = AssignmentBook.holder(vehicleId: unitId), holder.driverId != driver.id {
            return nil
        }
        return vehicle
    }

    /// The unit the driver must take today: the substitute while it lasts, the titular one otherwise.
    var assignedVehicle: Vehicle? {
        guard let unitAssignment else { return nil }
        return vehicles.first { $0.id == unitAssignment.vehicleId }
    }

    var hasAssignedUnit: Bool { assignedVehicle != nil }

    /// Unit shown on the home screen: the one being driven, or the fixed one.
    var displayVehicle: Vehicle? { activeVehicle ?? assignedVehicle }

    // MARK: - Session scope

    var isAuthenticated: Bool { session != nil }

    /// Demonstration credential behind the session, when there is one.
    ///
    /// A Supabase session resolves to `nil` here on purpose: no `StaffAccount` is
    /// fabricated for it, because inventing a directory entry would put a password-bearing
    /// demo model back in the path of a real identity.
    var currentAccount: StaffAccount? { StaffDirectory.account(id: session?.accountId) }

    /// Identity proved by the backend for the open session, if it came from there.
    var currentPrincipal: SessionPrincipal? { session?.principal }

    /// The one test that separates a backend session from a demonstration one.
    var isBackendSession: Bool { session?.principal != nil }

    // MARK: - Execution environment

    /// The environment this session is running in, read live from the single source.
    ///
    /// Read, never stored. A capability that cached this would answer for whichever
    /// environment happened to be active when the session opened — which is precisely the
    /// failure 15B.13.2.1 fixes: entering the laboratory had to be done *before* signing
    /// in, because after signing in nothing asked again.
    var environment: LabMode { environmentSource.mode }

    /// Whether this session's records answer to a real station.
    ///
    /// Two conditions, and both are necessary. A proved identity is not enough on its own:
    /// inside the laboratory there is no station to contradict, the amber badge says so on
    /// every screen, and refusing to simulate there leaves a test account with an app it
    /// cannot exercise. And the laboratory is not enough on its own either: a demonstration
    /// credential simulates in both environments, as it always has.
    ///
    /// This is the single place the three boundaries below are decided from, so the
    /// environment cannot be honoured by one of them and ignored by another.
    var runsAgainstStation: Bool { isBackendSession && environment == .production }

    // MARK: - Financial boundary

    /// Whether this session may mint financial state locally.
    ///
    /// A demonstration session may: fabricating a contract or an income is the whole
    /// point of a flow that has no server behind it yet. A backend identity may not.
    /// Anything shown as money to a proved driver has to have come from the authority
    /// that owes it, and while there is no financial layer on the server the honest
    /// answer is that the operation is unavailable — not an invented contract that a
    /// settlement will happily subtract.
    ///
    /// This is the capability the writers ask. It lives here, not in the views: the
    /// session is the only thing that can answer it, and a screen that decided this for
    /// itself would be one refactor away from getting it wrong.
    var canSimulateFinancialState: Bool { !runsAgainstStation }

    /// Provenance every financial record this session produces is stamped with, and the
    /// one a settlement built from those records will accept.
    var ledgerOrigin: RecordOrigin { canSimulateFinancialState ? .simulated : .backend }

    // MARK: - Operational coordination boundary

    /// Whether this session may run the coverage workflow locally.
    ///
    /// Money was the first boundary; coordination is the second. An absence request, a
    /// claimed guard and a shift swap are decisions shared with a supervisor and a
    /// station, and this app writes them into one blob on one device. A demonstration
    /// session may do that: walking the chain end to end is the point. A proved identity
    /// may not, because no coverage service exists on the server yet, and a request that
    /// reaches nobody must never be shown as sent.
    ///
    /// Deliberately a second property instead of a reuse of the financial one. They
    /// answer alike today only because both backends are missing; coverage may well
    /// arrive before settlement, and when it does exactly one of them flips.
    var canSimulateOperationalCoordination: Bool { !runsAgainstStation }

    /// The capability the coverage board operates under for the open session.
    ///
    /// Asked here rather than decided in a view: the session is the only thing that can
    /// answer it, and a screen that judged this for itself would be one refactor away
    /// from getting it wrong.
    var coordinationCapability: CoordinationCapability {
        canSimulateOperationalCoordination ? .localWorkflow : .stationRequired
    }

    // MARK: - Unit assignment boundary

    /// Whether this session may create fleet inventory and unit assignments locally.
    ///
    /// The third boundary, and a third property rather than a reuse of the other two.
    /// A unit is not money and it is not a coverage request: it is a physical vehicle a
    /// supervisor hands to a person, and the station's system is the only authority that
    /// can say who holds which one. A demonstration session mints them freely, because a
    /// demonstration with no unit has nothing to demonstrate. A proved identity gets what
    /// the server assigned, which today is nothing — and "todavía no tienes unidad" is a
    /// true sentence, while a borrowed TEV-014 is not.
    var canSimulateUnitAssignment: Bool { !runsAgainstStation }

    /// The capability every read and write of the assignment book is judged against.
    var unitAssignmentCapability: UnitAssignmentCapability {
        canSimulateUnitAssignment ? .localSimulation : .stationRequired
    }

    // MARK: - Operational cycle boundary

    /// Whether this session may open, close and report the shift cycle locally.
    ///
    /// The fourth boundary, and a fourth property on purpose — the three above are not
    /// reused here even though all four read the same expression today. A unit assignment
    /// is a supervisor writing a row; a shift is the station certifying that a person
    /// drove for nine hours, and an incident is a report a human being has to receive.
    /// Those services arrive on different days: assignment is the one already being wired,
    /// and when it lands exactly one of these flips while the rest keep refusing.
    ///
    /// A demonstration or laboratory session runs the whole cycle, unchanged. A proved
    /// identity in production does not: there is nothing on the other end to register a
    /// start, so an `ActiveShift` minted here would be a nine-hour block the station never
    /// saw, feeding a history, a settlement and four bonuses.
    var canRunOperationalCycle: Bool { !runsAgainstStation }

    /// The capability the shift cycle and the incident report are judged against.
    var operationalCapability: OperationalCapability {
        canRunOperationalCycle ? .localWorkflow : .stationRequired
    }

    /// Provenance every operational record this session produces is stamped with, and the
    /// one restoration will accept back.
    var operationalOrigin: OperationalRecordOrigin { operationalCapability.origin }

    // MARK: - Notice boundary

    /// Whether this session may write into the driver's bell in the station's voice.
    ///
    /// The fifth boundary, and the smallest thing any of them guards — which is exactly
    /// why it needs its own. The four above stop records: a contract, a claimed guard, an
    /// assignment, a shift. A notice is not a record; it is a sentence addressed to the
    /// driver, and it is how every one of those records *announces itself*. "Depósito en
    /// efectivo notificado a gerencia" is not a row somebody might later read — it is the
    /// app telling a person, in the second person, that a manager has their receipt.
    ///
    /// It gets its own property rather than riding on the others because its future is
    /// the opposite of theirs. The others end when a service lands and the app starts
    /// writing real records. This one ends when the station starts *sending* — notices
    /// that correspond to no local record at all: a bay closed, a policy changed, a
    /// summons. That day this flips on its own, and the four below may still be refusing.
    var canPublishStationNotices: Bool { !runsAgainstStation }

    /// Whose voice the bell speaks in for the open session.
    var noticeAuthority: NoticeAuthority {
        canPublishStationNotices ? .localBulletin : .stationPublished
    }

    /// What the bell may show. Filtered by provenance, never emptied by deletion: a
    /// laboratory notice stays in the laboratory blob and returns with it.
    var visibleNotices: [Notice] {
        NoticeRules.visible(notices, authority: noticeAuthority)
    }

    /// Whether the shift standing in memory is one this session may act on.
    ///
    /// A `.simulated` shift left open inside the laboratory is not closeable from
    /// production: it is state of another operation that the container policy keeps, and
    /// closing it here would file a real `ShiftRecord` built out of a simulation.
    var canActOnActiveShift: Bool {
        guard let activeShift else { return false }
        return OperationalRecordRules.adopts(
            owner: activeShift.driverId,
            origin: activeShift.origin,
            driverId: driver.id,
            capability: operationalCapability
        )
    }

    var currentRole: StaffRole? { session?.role }

    var currentStation: Station? { StaffDirectory.station(id: session?.stationId) }

    /// Account allowed to unlock this device with Face ID, if any.
    var enrolledAccount: StaffAccount? { StaffDirectory.account(id: enrolledAccountId) }

    /// Interfaces are opened by role only: a driver can never render a supervisor screen.
    func hasAccess(to role: StaffRole) -> Bool { session?.role == role }

    /// The driver profile is exposed only inside a driver session.
    var driverProfile: Driver? {
        guard let account = currentAccount, account.role == .driver, account.driverId == driver.id else { return nil }
        return driver
    }

    // MARK: - Derived values

    /// Time the app obeys. It never comes from the phone: in production it is real time
    /// and in a simulation it is the logical time of the test environment, shared by every
    /// role and every device.
    ///
    /// **A pure read.** It answers what hour it is and registers no SwiftUI dependency.
    ///
    /// It used to read `ClockSignal.generation` first. That was load-bearing at the time and
    /// is deliberately gone now: one indiscriminate counter meant any adopted clock state
    /// invalidated every reader of `store.now` at once, across all seven roles — and worse,
    /// screens inherited temporal correctness by accident, through a side effect none of
    /// them named. Views that genuinely follow the clock now say so, one at a time, with
    /// `TimeScope` or `ClockAnchor`.
    ///
    /// Use this for **action time**: the instant a decision is taken, a form is preloaded, a
    /// snapshot is rebuilt or a seed key is computed. Never to make something on screen move
    /// by itself — nothing observes this any more, and nothing should.
    var now: Date {
        AppClock.now()
    }

    var activeVehicle: Vehicle? {
        guard let shift = activeShift else { return nil }
        return vehicles.first { $0.id == shift.vehicleId }
    }

    /// The badge on the bell. Counted over what may be shown, so a simulated notice can
    /// never leave a proved identity with an unread mark on an empty list.
    var unreadNoticeCount: Int { visibleNotices.filter { !$0.read }.count }

    var hasCredit: Bool { credit != nil }

    /// Transparent contract metrics for the credit panel.
    var creditMetrics: CreditMetrics? {
        guard let credit else { return nil }
        return CreditProgram.metrics(for: credit, now: now)
    }

    var goals: ShiftRules.Goals { ShiftRules.goals(for: driver.group) }

    func elapsedSeconds(at date: Date) -> Int {
        guard let shift = activeShift else { return 0 }
        return max(0, Int(date.timeIntervalSince(shift.startedAt)))
    }

    func estimatedKmDriven(at date: Date) -> Int {
        Int((Double(elapsedSeconds(at: date)) / 60 * Self.simulatedKmPerMinute).rounded())
    }

    var capturedPhotoCount: Int { activeShift?.photos.count ?? 0 }

    /// The start of shift only needs the odometer and the battery readings.
    var isInspectionComplete: Bool {
        guard let shift = activeShift else { return false }
        return InspectionSlot.driverSlots.allSatisfy { shift.photos[$0.rawValue] != nil }
    }

    /// Monday → Sunday late-minute log, the "bitácora" shown in Historial.
    struct LateDay: Identifiable, Sendable {
        let date: Date
        let label: String
        let minutes: Int
        let paidBackMinutes: Int
        let hasShift: Bool

        var id: Date { date }
        var pendingMinutes: Int { max(0, minutes - paidBackMinutes) }
    }

    func weeklyLateBreakdown(reference: Date) -> [LateDay] {
        let calendar = ShiftRules.calendar
        let start = ShiftRules.weekStart(for: reference)
        return (0..<7).compactMap { offset in
            guard let day = calendar.date(byAdding: .day, value: offset, to: start) else { return nil }
            let record = history.first { ShiftRules.isSameDay($0.startedAt, day) }
            return LateDay(
                date: day,
                label: Fmt.dayShort(day),
                minutes: record?.lateMinutes ?? 0,
                paidBackMinutes: record?.paidBackMinutes ?? 0,
                hasShift: record != nil
            )
        }
    }

    func weeklyLateDebt(reference: Date) -> Int {
        weeklyLateBreakdown(reference: reference).reduce(0) { $0 + $1.pendingMinutes }
    }

    func earnedToday(reference: Date) -> Int {
        let fromIncomes = incomes
            .filter { ShiftRules.isSameDay($0.date, reference) }
            .reduce(0) { $0 + $1.amountMxn }
        let fromClosedShifts = history
            .filter { ShiftRules.isSameDay($0.startedAt, reference) }
            .reduce(0) { $0 + $1.earningsMxn }
        return max(fromIncomes, fromClosedShifts, activeShift?.earningsMxn ?? 0)
    }

    func tripsToday(reference: Date) -> Int {
        let fromIncomes = incomes
            .filter { ShiftRules.isSameDay($0.date, reference) }
            .reduce(0) { $0 + $1.trips }
        return max(fromIncomes, activeShift?.trips ?? 0)
    }

    func earnedThisWeek(reference: Date) -> Int {
        incomes
            .filter { ShiftRules.isInSameWeek($0.date, as: reference) }
            .reduce(0) { $0 + $1.amountMxn }
    }

    struct DayEarnings: Identifiable, Sendable {
        let label: String
        let amount: Int
        let isToday: Bool
        let date: Date

        var id: Date { date }
    }

    func weeklyEarningsByDay(reference: Date) -> [DayEarnings] {
        let calendar = ShiftRules.calendar
        let start = ShiftRules.weekStart(for: reference)
        return (0..<7).compactMap { offset in
            guard let day = calendar.date(byAdding: .day, value: offset, to: start) else { return nil }
            let amount = incomes
                .filter { ShiftRules.isSameDay($0.date, day) }
                .reduce(0) { $0 + $1.amountMxn }
            return DayEarnings(
                label: Fmt.dayShort(day),
                amount: amount,
                isToday: ShiftRules.isSameDay(day, reference),
                date: day
            )
        }
    }

    // MARK: - Session

    /// Opens the session of an identity already proved by the backend.
    ///
    /// Deliberately a separate door from the demonstration one: it never consults
    /// `StaffDirectory`, never adds an account to it, and never resolves the driver
    /// through `MockData`. Everything the session shows about the person comes from the
    /// `principal` the server returned.
    ///
    /// The device is **not** enrolled for biometric unlock here. Repeating this sign-in
    /// without the password would require keeping a credential, which this phase does not
    /// do; Face ID keeps working exactly as before, for demonstration accounts only.
    ///
    /// Throws when a driver's membership is incomplete, before any state is touched.
    func signIn(principal: SessionPrincipal, method: SignInMethod) throws {
        // Built first: if the membership is incomplete this throws and the store is left
        // exactly as it was, with no half-open session.
        let profile: Driver? = principal.role == .driver
            ? try Self.sessionDriver(from: principal)
            : nil

        // Whatever is standing in memory belongs to the identity that is leaving. It is
        // written under **its own** key before anything is swapped, so opening a backend
        // session never costs the demonstration state a single record.
        persist()

        // The session opens in whatever environment the device is in, which is not
        // necessarily the one the last state was loaded from.
        adoptedEnvironment = environmentSource.mode

        // From here the store holds this identity's operational state and nothing else.
        adoptIdentityState(profileId: principal.profileId)

        if let profile {
            driver = profile
        }

        session = StaffSession(
            accountId: principal.profileId,
            role: principal.role,
            stationId: principal.stationId,
            method: method,
            startedAt: Date(),
            principal: principal
        )
        awaitsCredentialChoice = false
        reloadAssignment()
        persist()
    }

    /// Builds the driver profile of a backend session from the principal alone.
    ///
    /// `password` is the empty string because `Driver` still declares that legacy field;
    /// it is a placeholder for a model shape, never a stored credential, and the password
    /// typed on the access screen never reaches this point.
    ///
    /// `authorizedVehicleIds` is empty because no real assignment exists yet for this
    /// person. An invented unit would be worse than none: the driver would see a vehicle
    /// the station never gave them.
    nonisolated private static func sessionDriver(
        from principal: SessionPrincipal
    ) throws -> Driver {
        guard let stationId = principal.stationId, !stationId.isEmpty else {
            throw SessionOpenError.missingStation
        }
        guard let stationName = principal.stationName, !stationName.isEmpty else {
            throw SessionOpenError.missingStationName
        }
        guard let group = principal.shiftGroup else {
            throw SessionOpenError.missingShiftGroup
        }
        guard let slot = principal.shiftSlot else {
            throw SessionOpenError.missingShiftSlot
        }

        return Driver(
            id: principal.profileId,
            name: principal.name,
            employeeNumber: principal.employeeNumber,
            email: principal.email,
            password: "",
            photoAsset: "rideshare_driver_portrait",
            stationId: stationId,
            station: stationName,
            group: group,
            slot: slot,
            authorizedVehicleIds: []
        )
    }

    /// Opens the session for an already authenticated account and links the device
    /// so future biometric unlocks resolve to this same credential.
    func signIn(account: StaffAccount, method: SignInMethod) {
        if let profile = MockData.driver(for: account) {
            driver = profile
        } else if LabRuntime.isTest, account.role == .driver {
            driver = MockData.driver
        }
        defer { reloadAssignment() }
        session = StaffSession(
            accountId: account.id,
            role: account.role,
            stationId: account.stationId,
            method: method,
            startedAt: Date()
        )
        enrolledAccountId = account.id
        awaitsCredentialChoice = false
        persist()
    }

    /// Loads the operational state that belongs to one backend identity, and only that.
    ///
    /// Two independent guarantees, on purpose. The storage key already separates one
    /// driver from another, and on top of it every record is checked against the
    /// `driverId` it carries. A driver who has never worked — no stored state at all —
    /// lands on a genuinely empty operation: no shift, no history, no income, no incident,
    /// no credit, no unit.
    ///
    /// `enrolledAccountId` and `clockOffsetMinutes` are deliberately left alone: the
    /// biometric link and the simulation clock belong to the device, not to the driver.
    private func adoptIdentityState(profileId: String) {
        // The capability of the environment the state is being read **for**. Taken from
        // `adoptedEnvironment` rather than from `operationalCapability` because this runs
        // mid-swap, before the session is necessarily standing: inside the laboratory a
        // proved identity keeps its simulated cycle, in production it keeps none of it.
        let capability: OperationalCapability = adoptedEnvironment == .production
            ? .stationRequired
            : .localWorkflow
        // Resolved from the same environment, separately on purpose: the two boundaries
        // answer alike today and are expected to diverge — a station can start publishing
        // notices long before it can certify a shift.
        let authority: NoticeAuthority = adoptedEnvironment == .production
            ? .stationPublished
            : .localBulletin
        let owned = Self.ownedState(
            Self.restore(
                key: Self.identityStorageKey(profileId: profileId, environment: adoptedEnvironment),
                defaults: defaults
            ),
            driverId: profileId,
            capability: capability,
            noticeAuthority: authority
        )
        vehicles = owned.vehicles
        activeShift = owned.activeShift
        history = owned.history
        incomes = owned.incomes
        incidents = owned.incidents
        notices = owned.notices
        credit = owned.credit
        supervisorReports = owned.supervisorReports
        recoveryBookings = owned.recoveryBookings
        notifiedBonusWeeks = owned.notifiedBonusWeeks
        // Resolved again from the assignment book, which is keyed by driver.
        unitAssignment = nil
    }

    /// Brings the demonstration state back into memory when a backend session ends.
    ///
    /// Without this the empty operation of the backend driver would be the thing standing
    /// in memory when the next `persist()` writes to the demonstration key — which would
    /// erase the demo data instead of isolating it.
    private func adoptDemoState() {
        driver = MockData.driver
        if let stored = Self.restore(key: Self.demoStorageKey, defaults: defaults) {
            enrolledAccountId = stored.enrolledAccountId
            applyOperational(stored)
        } else {
            seedDemoState()
        }
        unitAssignment = nil
    }

    /// Closes the session and returns to the access screen. The automatic scan is held
    /// back so another role can be identified instead of re-entering the same one.
    func signOut() {
        let wasBackendSession = isBackendSession
        // Saved under the key of the identity that is leaving, before it stops being the
        // current one.
        persist()
        session = nil
        awaitsCredentialChoice = true
        if wasBackendSession {
            adoptDemoState()
            reloadAssignment()
        }
        persist()
    }

    /// Removes the biometric link so the next access requires full credentials.
    func forgetDevice() {
        let wasBackendSession = isBackendSession
        persist()
        enrolledAccountId = nil
        session = nil
        awaitsCredentialChoice = true
        if wasBackendSession {
            adoptDemoState()
            enrolledAccountId = nil
            reloadAssignment()
        }
        persist()
    }

    /// Rebuilds the operational state from the active environment. Called whenever the
    /// laboratory changes the world so every interface reflects it immediately.
    func adoptEnvironment() {
        defer { reloadAssignment() }

        // The switch itself, and the only place it happens.
        //
        // A proved identity keeps its session, its credentials and its driver profile
        // across this: the environment changes underneath the same person. What is
        // exchanged is the operational blob — written under the key of the environment
        // being left, read from the key of the one being entered. Nothing is deleted on
        // either side, so the way out of the laboratory costs the real operation nothing,
        // and the way in costs the experiment nothing.
        let previous = adoptedEnvironment
        let current = environmentSource.mode
        if previous != current {
            persist(key: storageKey(for: previous))
            adoptedEnvironment = current
            if let profileId = session?.principal?.profileId {
                adoptIdentityState(profileId: profileId)
            }
        }

        // Same reasoning as in `init`: the session outlives the environment switch, so the
        // profile is resolved from the credential and only falls back to the
        // environment's default driver when the credential has none.
        //
        // A backend session is exempt: its driver was proved by the server and no
        // environment switch may replace that person with a seeded or laboratory one.
        if session?.principal == nil {
            driver = MockData.driver
            adoptSessionDriver()
        }
        // The environment is a **demonstration** world: switching it may not hand its
        // catalogue to an identity the server never sent one to. This was the documented
        // contradiction — with an empty inventory every unit fell through to `incoming`
        // and the whole demo fleet landed on a proved driver.
        let source = UnitAssignmentRules.catalogue(MockData.vehicles, capability: unitAssignmentCapability)
        let activeVehicleId = activeShift?.vehicleId

        vehicles = source.map { incoming in
            guard let kept = vehicles.first(where: { $0.id == incoming.id }) else { return incoming }
            // A unit inside a running shift keeps its live readings; every other unit
            // follows the environment, so lab edits land immediately.
            guard kept.id != activeVehicleId, LabRuntime.isTest else { return kept }
            return incoming
        }

        if let shift = activeShift, !vehicles.contains(where: { $0.id == shift.vehicleId }) {
            activeShift = nil
        }
        persist()
    }

    /// Wipes every operational record of the driver interface, leaving it at zero.
    ///
    /// "At zero" means different things per session, and both are literal. A
    /// demonstration one is rebuilt on the seeded catalogue so the world stays walkable;
    /// a proved identity is left with no inventory at all, because a wipe that ends with
    /// a fleet the station never sent is not a wipe.
    func clearOperationalData() {
        let capability = unitAssignmentCapability
        vehicles = UnitAssignmentRules.catalogue(MockData.vehicles, capability: capability)
        activeShift = nil
        history = []
        incomes = []
        incidents = []
        notices = []
        credit = nil
        supervisorReports = []
        recoveryBookings = []
        notifiedBonusWeeks = []
        clockOffsetMinutes = 0
        // The book is shared by the whole device and a proved identity owns no row in it.
        // Wiping it from here would erase the station's demonstration assignments — other
        // people's records — as a side effect of clearing this driver's own operation.
        if capability.allowsLocalSimulation {
            driver = MockData.driver
            AssignmentBook.clear()
        }
        unitAssignment = nil
        persist()
    }

    func setClockOffset(minutes: Int) {
        clockOffsetMinutes = minutes
        persist()
    }

    /// Keeps the persisted offset in step with the logical hour.
    ///
    /// This is **not** the invalidation mechanism any more. An integer number of minutes
    /// cannot express a second, a speed, a pause or a new revision landing on the same
    /// minute, so driving the interface from it left every one of those changes invisible.
    /// `ClockSignal` does the invalidating; this only maintains stored state.
    func syncSimulationClock() {
        let offset = AppClock.offsetMinutes()
        guard clockOffsetMinutes != offset else { return }
        clockOffsetMinutes = offset
        persist()
    }

    // MARK: - Start window

    var windowState: ShiftRules.WindowState { ShiftRules.windowState(driver: driver, now: now) }

    /// The block the driver belongs to is already over: a running shift has to be closed.
    var isWorkdayClosed: Bool { ShiftRules.isPastClose(slot: driver.slot, now: now) }

    var startWindow: (opensAt: Date, closesAt: Date) { ShiftRules.startWindow(slot: driver.slot, now: now) }

    /// Sends the blocking reason to the station so the supervisor can act on it.
    ///
    /// Returns whether the report was actually filed. There is no station service behind
    /// this yet — it writes a notice into local storage — so a proved identity gets a
    /// refusal instead of a "Reporte enviado a supervisión" nobody will ever read.
    @discardableResult
    func notifySupervisor(reason: String) -> Bool {
        guard canSimulateOperationalCoordination else { return false }
        pushNotice(
            kind: .station,
            title: "Reporte enviado a supervisión",
            body: reason
        )
        return true
    }

    func resetDemoData() {
        // Rebuilding the demonstration world for a proved identity would hand it a fleet,
        // a history, incomes and a fabricated contract in one call. There is nothing of
        // this driver's to reset locally: the wipe is the honest answer.
        guard canSimulateUnitAssignment else {
            clearOperationalData()
            return
        }
        guard !LabRuntime.isTest else {
            clearOperationalData()
            return
        }
        let seedDate = Date()
        let seedHistory = MockData.shiftHistory(driver: driver, now: seedDate)
        vehicles = MockData.syncOdometers(vehicles: MockData.vehicles, history: seedHistory)
        history = seedHistory
        incomes = MockData.incomeHistory(driver: driver, history: seedHistory)
        incidents = MockData.incidents(driver: driver, now: seedDate)
        notices = MockData.notices(now: seedDate)
        credit = MockData.credit(now: seedDate, driverId: driver.id)
        supervisorReports = MockData.supervisorReports(now: seedDate)
        recoveryBookings = []
        notifiedBonusWeeks = []
        activeShift = nil
        clockOffsetMinutes = 0
        CashDepositLedger.clear()
        CashChargeLedger.clear()
        persist()
    }

    // MARK: - Bonuses

    /// Platform quality score of the driver operating this device, when a source can
    /// answer for **them**.
    ///
    /// Resolved by identity, never by session type: only the seeded demonstration profile
    /// has a fixture behind it. Every other driver — backend or laboratory — has no score
    /// until a real rating arrives, and the bonus reports that honestly instead of
    /// borrowing someone else's stars.
    var platformRating: Double? { MockData.platformRating(for: driver) }

    /// Everything the bonus engine is allowed to look at, scoped to the current driver.
    ///
    /// The state is already isolated per identity, but the ownership test is repeated here
    /// because this is the boundary that decides whether someone is paid or punished.
    /// Supervisor reports carry no `driverId`; they are trusted only because they were
    /// written under this identity's own storage, and they are used solely as grounds to
    /// lose a week — never as proof that one was earned.
    private func bonusInput(reference: Date) -> BonusRules.EvaluationInput {
        let driverId = driver.id
        let capability = operationalCapability
        return BonusRules.EvaluationInput(
            driver: driver,
            goals: goals,
            history: OperationalRecordRules.history(history, driverId: driverId, capability: capability),
            incomes: incomes.filter { $0.driverId == driverId },
            reports: supervisorReports,
            activeShift: OperationalRecordRules.shift(activeShift, driverId: driverId, capability: capability),
            qualityScore: platformRating,
            schedule: NationalBonusBoard.current,
            now: reference
        )
    }

    func bonusEvaluations(reference: Date) -> [BonusEvaluation] {
        BonusRules.evaluateAll(bonusInput(reference: reference))
    }

    /// Money still collectable at month end with the current weekly evaluation.
    func bonusPayableMxn(reference: Date) -> Int {
        bonusEvaluations(reference: reference).reduce(0) { $0 + $1.payableMxn }
    }

    /// Everything the month can pay with the amounts the national administration has
    /// in force. Stations cannot alter this number.
    func bonusTotalMxn() -> Int {
        NationalBonusBoard.current.ceilingMxn
    }

    /// Raises the popup for the first closed week that broke a bonus, once only.
    ///
    /// Only a week the engine actually judged and failed can reach here. A week without
    /// evidence is `notEvaluated`, which is not a loss: it raises no popup, writes no
    /// notice and opens no recovery.
    @discardableResult
    func raiseBonusAlert(reference: Date) -> BonusAlert? {
        let evaluations = bonusEvaluations(reference: reference)
        for evaluation in evaluations {
            for result in evaluation.weeks where result.status == .lost {
                let id = "\(evaluation.kind.rawValue)-\(Fmt.monthKey(reference))-\(result.week.index)"
                guard !notifiedBonusWeeks.contains(id) else { continue }
                let message = "¡\(Fmt.firstName(driver.name)) has perdido el bono de \(evaluation.kind.shortName)! Agenda hoy tu lugar en el programa de recuperación de bonos"
                notifiedBonusWeeks.append(id)
                pushNotice(
                    kind: .reminder,
                    title: message,
                    body: "Semana \(result.week.index) (\(result.week.rangeLabel)): \(result.detail)."
                )
                return BonusAlert(id: id, kind: evaluation.kind, weekIndex: result.week.index, message: message)
            }
        }
        return nil
    }

    // MARK: - Recovery program

    func recoveryBooking(on day: Date) -> RecoveryBooking? {
        recoveryBookings.first { ShiftRules.isSameDay($0.date, day) }
    }

    var upcomingRecoveryBookings: [RecoveryBooking] {
        recoveryBookings.sorted { $0.date < $1.date }
    }

    /// Reserves a seat in the recovery programme.
    ///
    /// Refuses under a proved identity before anything is written, and the boundary it
    /// asks is the coordination one — deliberately reused, because this is literally the
    /// same act it was created for. Booking a recovery day is asking the station to hold
    /// a shift open for you on a date; an absence request and a claimed guard are the
    /// same sentence with different subjects. There is one desk on the other end, absent
    /// in the same way, and the day it exists all three become possible together.
    ///
    /// Nothing here is a permission problem: the driver is entitled to the programme.
    /// What is missing is the register that would hold the seat, so the seat is not
    /// promised.
    @discardableResult
    func bookRecovery(date: Date, slot: ShiftSlot, bonus: BonusKind) -> Bool {
        guard canSimulateOperationalCoordination else { return false }
        guard BonusRules.canBook(driver: driver, date: date, now: now) else { return false }
        guard recoveryBooking(on: date) == nil else { return false }

        let booking = RecoveryBooking(
            id: "rec-\(UUID().uuidString.prefix(8))",
            date: ShiftRules.calendar.startOfDay(for: date),
            slot: slot,
            bonus: bonus,
            createdAt: now
        )
        recoveryBookings.append(booking)
        pushNotice(
            kind: .station,
            title: "Reserva confirmada en recuperación de bonos",
            body: "\(Fmt.dateShort(booking.date).capitalized) · turno \(slot.label.lowercased()) \(slot.rangeLabel). Recuperas el bono de \(bonus.shortName)."
        )
        return true
    }

    func cancelRecovery(id: String) {
        recoveryBookings.removeAll { $0.id == id }
        persist()
    }

    // MARK: - Shift lifecycle

    func validateAssignment(vehicle: Vehicle, odometerKm: Int, batteryPct: Int) -> [AssignmentIssue] {
        ShiftRules.validateAssignment(
            driver: driver,
            vehicle: vehicle,
            now: now,
            odometerKm: odometerKm,
            batteryPct: batteryPct
        )
    }

    /// Step 1 of the start flow: sticker read against the assigned unit.
    func validateScannedUnit(vehicle: Vehicle) -> [AssignmentIssue] {
        ShiftRules.validateUnit(
            driver: driver,
            vehicle: vehicle,
            assignedVehicleId: unitAssignment?.vehicleId,
            now: now
        )
    }

    /// Step 2: photographed odometer, ±5 km against the registered reading.
    func validateOdometerReading(vehicle: Vehicle, reading: Int) -> AssignmentIssue? {
        ShiftRules.validateOdometer(vehicle: vehicle, reading: reading)
    }

    /// Step 3: photographed charge against the fleet minimum.
    func validateBatteryReading(_ reading: Int) -> AssignmentIssue? {
        ShiftRules.validateBattery(reading: reading)
    }

    /// Closes the three-step flow: opens the shift and files the captured evidence.
    ///
    /// **The whole write is behind one guard.** Opening a shift is not one record: it
    /// mints an `ActiveShift`, flips a vehicle to `.occupied`, writes `occupiedBy`,
    /// overwrites the unit's odometer and battery with numbers typed on this phone,
    /// files two photographs as evidence and may register a late arrival that costs a
    /// bonus. Every one of those is asserted to be a fact of the station's day. So the
    /// refusal is taken here, before the first of them.
    ///
    /// The unit checks stay after it and unchanged: inside a simulation the shift is
    /// still only openable on the unit actually assigned.
    @discardableResult
    func startShift(
        vehicle: Vehicle,
        odometerKm: Int,
        batteryPct: Int,
        odometerPhoto: Data?,
        batteryPhoto: Data?
    ) throws -> ActiveShift {
        guard canRunOperationalCycle else { throw OperationalMutationError.backendRequired }
        guard let assigned = unitAssignment, assigned.vehicleId == vehicle.id else {
            throw UnitAssignmentError.unitNotAssigned
        }
        guard vehicles.contains(where: { $0.id == vehicle.id }) else {
            throw UnitAssignmentError.unitNotAssigned
        }
        let shift = assign(vehicle: vehicle, odometerKm: odometerKm, batteryPct: batteryPct)
        if let odometerPhoto { saveInspectionPhoto(slot: .odometer, data: odometerPhoto) }
        if let batteryPhoto { saveInspectionPhoto(slot: .battery, data: batteryPhoto) }
        return activeShift ?? shift
    }

    /// The write itself, with no boundary of its own.
    ///
    /// Private since 15B.13.3: it was reachable from anywhere, and it is the method that
    /// actually opens a shift and takes a vehicle. Every caller now has to cross
    /// `startShift` — where the refusal lives — instead of arriving here directly.
    @discardableResult
    private func assign(vehicle: Vehicle, odometerKm: Int, batteryPct: Int) -> ActiveShift {
        let startedAt = now
        let scheduled = ShiftRules.scheduledStart(slot: driver.slot, on: startedAt)
        let shift = ActiveShift(
            id: "shift-\(UUID().uuidString.prefix(8))",
            driverId: driver.id,
            vehicleId: vehicle.id,
            group: ShiftRules.group(for: startedAt),
            slot: driver.slot,
            scheduledStartAt: scheduled,
            startedAt: startedAt,
            lateMinutes: ShiftRules.lateMinutes(scheduled: scheduled, actual: startedAt),
            startOdometerKm: odometerKm,
            startBatteryPct: batteryPct,
            photos: [:],
            trips: 0,
            earningsMxn: 0,
            origin: operationalOrigin
        )

        activeShift = shift
        if let index = vehicles.firstIndex(where: { $0.id == vehicle.id }) {
            vehicles[index].status = .occupied
            vehicles[index].occupiedBy = driver.id
            vehicles[index].odometerKm = odometerKm
            vehicles[index].batteryPct = batteryPct
        }

        if shift.lateMinutes > 0 {
            pushNotice(
                kind: .reminder,
                title: "Inicio de turno con atraso",
                body: "Iniciaste \(shift.lateMinutes) minutos después de la hora programada. Se registró en tu bitácora."
            )
        }

        persist()
        return shift
    }

    /// Files evidence onto the open shift.
    ///
    /// Gated too, even though a production session cannot have a shift to attach to: a
    /// photograph stored against a shift record *is* the evidence the station is told it
    /// has, and a legacy simulated shift standing in memory must not be able to collect
    /// more of it under a proved identity.
    func saveInspectionPhoto(slot: InspectionSlot, data: Data) {
        guard canRunOperationalCycle, canActOnActiveShift else { return }
        guard var shift = activeShift else { return }
        shift.photos[slot.rawValue] = data
        activeShift = shift
        persist()
    }

    /// Files an income the driver declares.
    ///
    /// This is the most load-bearing write in the app and the reason 15B.10 exists. An
    /// income does not merely add pesos: it is what makes the week count as worked, and
    /// a worked week unlocks the station deduction and satisfies the gate the bonuses
    /// stand on. One fabricated entry moves four bonuses out of "sin evaluar" and into
    /// payable. So a session that cannot vouch for the money cannot file it.
    func registerIncome(
        amountMxn: Int,
        trips: Int,
        platform: IncomePlatform,
        evidence: Data?,
        note: String? = nil
    ) throws {
        guard canSimulateFinancialState else { throw FinancialMutationError.backendRequired }
        appendIncome(amountMxn: amountMxn, trips: trips, platform: platform, evidence: evidence, note: note)
    }

    /// The write itself, with no boundary of its own.
    ///
    /// Separated from `registerIncome` so that every caller has to have crossed the
    /// boundary explicitly before reaching it, rather than swallowing a thrown refusal
    /// with `try?` and leaving no trace of the decision.
    private func appendIncome(
        amountMxn: Int,
        trips: Int,
        platform: IncomePlatform,
        evidence: Data?,
        note: String?
    ) {
        let entry = IncomeEntry(
            id: "inc-\(UUID().uuidString.prefix(8))",
            driverId: driver.id,
            origin: ledgerOrigin,
            shiftId: activeShift?.id,
            date: now,
            amountMxn: amountMxn,
            trips: trips,
            platform: platform,
            evidence: evidence,
            note: note
        )
        incomes.insert(entry, at: 0)

        if var shift = activeShift {
            shift.earningsMxn += amountMxn
            shift.trips += trips
            activeShift = shift
        }
        persist()
    }

    /// The account direction publishes for cash that could not be charged by card.
    ///
    /// Optional, because `NationalCashBoard` is a demonstration channel: its default is a
    /// fictitious BBVA account written into the source, and the only desk that can
    /// overwrite it is the national screen of this same app. Nothing in it was published
    /// by an authority a backend session can appeal to, so for a proved identity the
    /// honest answer is that there is no account yet — not a plausible one.
    var cashDepositAccount: CashDepositAccount? {
        guard canSimulateFinancialState else { return nil }
        return NationalCashBoard.current
    }

    /// Cash trips the platform reported and that are still in the driver's hands.
    ///
    /// Read through the ledger of this session. A backend identity reads the `.backend`
    /// book, which nothing writes to yet, so it sees none of the charges this device
    /// minted — without a single one of them being deleted.
    var openCashCharges: [CashCharge] {
        CashChargeLedger.open(driverId: driver.id, origin: ledgerOrigin)
    }

    /// Simulates the platform reporting a trip settled in cash during the shift.
    ///
    /// Throws under a proved identity. This mints a debt: the charge becomes a deduction
    /// on the week the moment its day ends, so standing in for the platform here would
    /// take real money from someone on the strength of a random trip folio.
    @discardableResult
    func syncCashChargeFromPlatform(amountMxn: Int) throws -> CashCharge {
        guard canSimulateFinancialState else { throw FinancialMutationError.backendRequired }

        let charge = CashChargeLedger.make(
            driverId: driver.id,
            stationId: driver.stationId,
            amountMxn: amountMxn,
            now: now
        )
        CashChargeLedger.add(charge)
        pushNotice(
            kind: .station,
            title: "Viaje cobrado en efectivo",
            body: "\(charge.tripReference) por \(Fmt.mxn(amountMxn)). Deposítalo hoy antes de las 23:59:59 o se descontará de tus ingresos de la semana."
        )
        return charge
    }

    /// Closes every cash charge whose day already ended without a deposit. From here the
    /// amount stops being a pending deposit and becomes a discount on the week, visible
    /// in the wallet as "Cobro de viaje en efectivo".
    ///
    /// The list it works from is already scoped to this session's ledger, and the test is
    /// repeated below anyway: this is the exact step where a charge stops being a pending
    /// deposit and becomes money taken off a week, and a fixture must never be able to
    /// make that crossing inside a real identity's book.
    @discardableResult
    func chargeBackExpiredCashCharges() -> [CashCharge] {
        let ledger = ledgerOrigin
        let expired = openCashCharges.filter {
            $0.origin == ledger && now > CashChargeRules.deadline(for: $0)
        }
        guard !expired.isEmpty else { return [] }

        for charge in expired {
            CashChargeLedger.markChargedBack(id: charge.id, at: now)
            pushNotice(
                kind: .credit,
                title: "\(CashChargeRules.recoveryConcept) · \(Fmt.mxn(charge.amountMxn))",
                body: "El viaje \(charge.tripReference) del \(Fmt.dateShort(charge.generatedAt)) no se depositó el mismo día. El monto se descuenta de tus ingresos al cierre de la semana."
            )
        }
        return expired
    }

    /// Files a cash deposit: the income enters the day, the slip stays attached and the
    /// manager of the station is notified in the same movement. Cash is not an authorized
    /// way to charge, so every peso received in hand has to leave a trace.
    ///
    /// Throws under a proved identity, before anything is written. Filing a deposit is
    /// the app asserting that money reached the network's account; done locally that is a
    /// receipt for a transfer nobody made, against a bank account no authority published.
    @discardableResult
    func registerCashDeposit(
        charge: CashCharge,
        declaredMxn: Int,
        detectedMxn: Int?,
        match: DepositMatch,
        accountMatch: DepositMatch,
        detectedAccount: String?,
        slip: Data?
    ) throws -> CashDeposit {
        guard canSimulateFinancialState, let account = cashDepositAccount else {
            throw FinancialMutationError.backendRequired
        }

        let deposit = CashDeposit(
            id: "dep-\(UUID().uuidString.prefix(8))",
            origin: ledgerOrigin,
            stationId: driver.stationId,
            driverId: driver.id,
            driverName: driver.name,
            vehicleNumber: displayVehicle?.internalNumber ?? "Sin unidad",
            declaredMxn: declaredMxn,
            detectedMxn: detectedMxn,
            match: match,
            accountMatch: accountMatch,
            detectedAccount: detectedAccount,
            bank: account.bank,
            clabe: account.clabe,
            createdAt: now,
            slip: slip,
            acknowledgedAt: nil
        )
        CashDepositLedger.record(deposit)
        CashChargeLedger.markDeposited(id: charge.id, at: now)

        // The guard above is the boundary now, so this is reached only inside a session
        // that may simulate. The call stays unconditional to keep the deposit and the
        // income it books inseparable: a slip filed without its matching entry would be
        // money that left the driver's hands and never appeared in the week.
        appendIncome(
            amountMxn: declaredMxn,
            trips: 0,
            platform: .cash,
            evidence: slip,
            note: "\(charge.tripReference) · depósito en \(account.bank)"
        )

        pushNotice(
            kind: .station,
            title: "Depósito en efectivo notificado a gerencia",
            body: "\(Fmt.mxn(declaredMxn)) del viaje \(charge.tripReference) depositados en \(account.bank). El gerente de \(driver.station) recibió el comprobante."
        )
        return deposit
    }

    /// Files an incident report.
    ///
    /// Throws under a proved identity in production, before the record exists. The
    /// notice this raises says "Incidencia enviada a la estación" and the row lands as
    /// `.open`, which every screen renders as *waiting for supervision*. There is no
    /// supervision service behind it: after a collision with a third party, a driver who
    /// believes the station was notified and is waiting is in a materially worse position
    /// than one who knows they still have to call.
    ///
    /// The screen stays open and the photographs stay capturable — as a draft the caller
    /// holds, never as `incidents`, which is the list that means "reported".
    func reportIncident(kind: IncidentKind, description: String, photos: [Data]) throws {
        guard canRunOperationalCycle else { throw OperationalMutationError.backendRequired }
        let vehicle = activeVehicle ?? vehicles.first
        let incident = Incident(
            id: "inci-\(UUID().uuidString.prefix(8))",
            driverId: driver.id,
            vehicleId: vehicle?.id ?? "—",
            vehicleInternalNumber: vehicle?.internalNumber ?? "—",
            kind: kind,
            createdAt: now,
            description: description,
            photos: photos,
            status: .open,
            origin: operationalOrigin
        )
        incidents.insert(incident, at: 0)
        pushNotice(
            kind: .station,
            title: "Incidencia enviada a la estación",
            body: "Tu reporte de \(kind.label.lowercased()) quedó en revisión."
        )
        persist()
    }

    /// Closes the open shift: files the record, releases the unit and returns the summary.
    ///
    /// Two refusals, and they are different questions. The first is the boundary: closing
    /// a shift writes the row a settlement multiplies and four bonuses are judged on, and
    /// there is no station to certify it. The second is about the shift itself — a
    /// `.simulated` one left open in the laboratory cannot be closed from production, or
    /// the exit from a simulation would mint a real closed shift out of it. Neither
    /// deletes anything: the simulated shift stays in its own container, closeable where
    /// it was opened.
    func finishShift(endOdometerKm: Int, endBatteryPct: Int, photo: Data?) throws -> ShiftSummary {
        guard canRunOperationalCycle else { throw OperationalMutationError.backendRequired }
        guard let shift = activeShift else {
            return ShiftSummary(
                kmDriven: 0,
                durationMinutes: 0,
                earningsMxn: 0,
                trips: 0,
                dailyGoalMxn: goals.dailyMxn,
                missingMxn: goals.dailyMxn,
                missingTrips: goals.tripsPerDay,
                lateMinutes: 0
            )
        }
        guard canActOnActiveShift else { throw OperationalMutationError.unauthoritativeShift }

        let endedAt = now
        let record = ShiftRecord(
            id: shift.id,
            driverId: shift.driverId,
            vehicleId: shift.vehicleId,
            vehicleInternalNumber: activeVehicle?.internalNumber ?? "—",
            group: shift.group,
            slot: shift.slot,
            scheduledStartAt: shift.scheduledStartAt,
            startedAt: shift.startedAt,
            endedAt: endedAt,
            lateMinutes: shift.lateMinutes,
            paidBackMinutes: 0,
            startOdometerKm: shift.startOdometerKm,
            endOdometerKm: endOdometerKm,
            startBatteryPct: shift.startBatteryPct,
            endBatteryPct: endBatteryPct,
            trips: shift.trips,
            earningsMxn: shift.earningsMxn,
            // Inherited from the shift, never recomputed from the current session: a
            // block opened inside a simulation stays a simulated block once closed.
            origin: shift.origin
        )

        history.insert(record, at: 0)
        if let index = vehicles.firstIndex(where: { $0.id == shift.vehicleId }) {
            vehicles[index].status = .available
            vehicles[index].occupiedBy = nil
            vehicles[index].odometerKm = endOdometerKm
            vehicles[index].batteryPct = endBatteryPct
        }
        if photo != nil {
            // Final odometer evidence is archived with the closed shift record.
            pushNotice(
                kind: .station,
                title: "Turno cerrado",
                body: "Entregaste \(record.vehicleInternalNumber) con \(Fmt.km(endOdometerKm)). Duración \(Fmt.durationText(record.durationMinutes))."
            )
        }
        activeShift = nil
        persist()

        return ShiftSummary(
            kmDriven: record.kmDriven,
            durationMinutes: record.durationMinutes,
            earningsMxn: record.earningsMxn,
            trips: record.trips,
            dailyGoalMxn: goals.dailyMxn,
            missingMxn: max(0, goals.dailyMxn - record.earningsMxn),
            missingTrips: max(0, goals.tripsPerDay - record.trips),
            lateMinutes: record.lateMinutes
        )
    }

    /// Applies paid-back minutes to the oldest pending late day of the current week.
    @discardableResult
    func payLateTime(minutes: Int) -> Int {
        var remaining = minutes
        var applied = 0
        let weekDays = weeklyLateBreakdown(reference: now).filter { $0.pendingMinutes > 0 }
        let pendingDates = weekDays.map(\.date)

        for index in history.indices where remaining > 0 {
            let record = history[index]
            guard pendingDates.contains(where: { ShiftRules.isSameDay($0, record.startedAt) }) else { continue }
            let pending = record.pendingLateMinutes
            guard pending > 0 else { continue }
            let pay = min(pending, remaining)
            history[index].paidBackMinutes += pay
            remaining -= pay
            applied += pay
        }

        if applied > 0 { persist() }
        return applied
    }

    // MARK: - Credit

    /// Signs a new contract: no down payment, immediate approval, first instalment in a week.
    ///
    /// Signing is a financial act, so it asks the boundary first. A proved identity gets
    /// a refusal it can show, not a contract nobody underwrote: approving a 390,000 peso
    /// loan is the server's to do, and until it can, saying so is the honest outcome.
    func requestCredit() throws {
        guard canSimulateFinancialState else { throw FinancialMutationError.backendRequired }
        guard credit == nil else { return }
        let reference = now
        let unit = vehicles.first { driver.authorizedVehicleIds.contains($0.id) }?.internalNumber ?? "por asignar"
        credit = CreditProgram.newAccount(
            now: reference,
            vehicleInternalNumber: unit,
            driverId: driver.id,
            origin: ledgerOrigin
        )
        pushNotice(
            kind: .credit,
            title: "Crédito aprobado",
            body: "Tu contrato del \(CreditProgram.vehicleModel) quedó firmado. El primer abono semanal se descuenta en 7 días."
        )
    }

    /// Loads the seeded mid-term contract so every metric of the panel can be reviewed.
    func loadCreditDemoProgress() throws {
        guard canSimulateFinancialState else { throw FinancialMutationError.backendRequired }
        credit = MockData.credit(now: now, driverId: driver.id)
        persist()
    }

    /// Returns the driver to the promotional banner state.
    func cancelCredit() {
        credit = nil
        persist()
    }

    // MARK: - Notices

    func markNoticeRead(id: String) {
        guard let index = notices.firstIndex(where: { $0.id == id }) else { return }
        notices[index].read = true
        persist()
    }

    /// Marks read only what this session can actually see. A notice belonging to another
    /// environment is not the reader's to dismiss.
    func markAllNoticesRead() {
        let visible = Set(visibleNotices.map(\.id))
        notices = notices.map { notice in
            guard visible.contains(notice.id) else { return notice }
            var updated = notice
            updated.read = true
            return updated
        }
        persist()
    }

    /// Publishes a notice in the station's voice — and the single frontier where that is
    /// decided, for every producer in the app.
    ///
    /// There are eighteen call sites across five stores, and auditing them one by one
    /// found the same shape each time: an operation succeeds locally and narrates itself
    /// as received by an authority. "Incidencia enviada a la estación." "Reserva
    /// confirmada." "Crédito aprobado." "Depósito notificado a gerencia." Gating each one
    /// separately would mean eighteen chances to forget, and every new feature would be
    /// a nineteenth. So the refusal lives here, once, where the sentence is minted.
    ///
    /// Returns whether anything was published, rather than throwing: a notice is a
    /// side effect of an operation that has already made its own decision, and forcing
    /// every caller into `try?` would hide the refusal instead of stating it. Callers
    /// that show a confirmation to the driver — `notifySupervisor`, `bookRecovery` — read
    /// this and say something true instead.
    @discardableResult
    func pushNotice(kind: NoticeKind, title: String, body: String) -> Bool {
        guard canPublishStationNotices else { return false }
        notices.insert(
            Notice(
                id: "not-\(UUID().uuidString.prefix(8))",
                kind: kind,
                title: title,
                body: body,
                createdAt: now,
                read: false,
                origin: noticeAuthority.origin
            ),
            at: 0
        )
        persist()
        return true
    }

    // MARK: - Persistence

    private func apply(_ state: PersistedState) {
        // A backend session is not restored from disk. Identity there is proved by a live
        // exchange with Supabase Auth, and no credential is kept to repeat it, so a
        // restored one would be a driver the app can no longer vouch for. It is dropped
        // and the access screen asks for credentials again; every operational record in
        // the same payload is kept untouched.
        if state.session?.principal == nil {
            session = state.session
        } else {
            session = nil
            // Never hand the relaunch to a biometric unlock of a different identity.
            awaitsCredentialChoice = true
        }
        enrolledAccountId = state.enrolledAccountId
        applyOperational(state)
        clockOffsetMinutes = state.clockOffsetMinutes
    }

    private func applyOperational(_ state: PersistedState) {
        vehicles = state.vehicles
        activeShift = state.activeShift
        history = state.history
        incomes = state.incomes
        incidents = state.incidents
        notices = state.notices
        credit = Self.demoAttributed(state.credit, driverId: driver.id)
        supervisorReports = state.supervisorReports
        recoveryBookings = state.recoveryBookings
        notifiedBonusWeeks = state.notifiedBonusWeeks
    }

    /// An operation with nothing in it. What a driver who has never worked must see.
    nonisolated private static func emptyOperationalState() -> PersistedState {
        PersistedState(
            session: nil,
            enrolledAccountId: nil,
            vehicles: [],
            activeShift: nil,
            history: [],
            incomes: [],
            incidents: [],
            notices: [],
            credit: nil,
            clockOffsetMinutes: 0,
            supervisorReports: [],
            recoveryBookings: [],
            notifiedBonusWeeks: []
        )
    }

    /// Names a contract stored before ownership existed.
    ///
    /// This only ever runs on the demonstration key — an identity restores through
    /// `ownedState`, which never adopts an unattributed contract — so a nameless
    /// contract can only have been written by a demonstration session, and belongs to
    /// the demonstration driver. It is never promoted out of `.simulated`: naming a
    /// fixture does not make it authoritative, it only lets the demo wallet keep
    /// discounting the contract Carlos already had.
    nonisolated private static func demoAttributed(_ credit: CreditAccount?, driverId: String) -> CreditAccount? {
        guard let credit else { return nil }
        guard !credit.isAttributed, credit.origin == .simulated else { return credit }
        return credit.attributed(to: driverId)
    }

    /// Keeps only what can be **proved** to belong to `driverId`.
    ///
    /// Records that carry a `driverId` are filtered by it. Everything else starts empty
    /// unless it was written under this identity's own key.
    ///
    /// **Credit restoration rule, adopted in 15B.10.** A stored contract is restored
    /// only if it names this driver as its owner **and** its provenance is `.backend`.
    /// Ownership on its own is not enough: a `.simulated` contract carrying the right
    /// owner string is still a fixture minted on this phone, and a matching string is
    /// not an authority vouching for a debt. Since nothing can legitimately produce a
    /// `.backend` contract yet, a backend session still ends up with no credit — but now
    /// because the rule says so, instead of because the model could not tell.
    ///
    /// The fleet inventory starts empty as well. A real station's units are the backend's
    /// to hand out; borrowing the demonstration catalogue is exactly how a driver ends up
    /// looking at a unit nobody ever assigned to them.
    nonisolated private static func ownedState(
        _ stored: PersistedState?,
        driverId: String,
        capability: OperationalCapability,
        noticeAuthority: NoticeAuthority
    ) -> PersistedState {
        var owned = emptyOperationalState()
        guard let stored else { return owned }

        // Deliberately **not** `stored.vehicles`. The comment above has said since 15B.10
        // that the inventory starts empty, but the code restored whatever was on disk — so
        // one demonstration catalogue leaking in through an environment switch became
        // permanent the moment `persist()` ran. Nothing is deleted: the stored array stays
        // on disk, it is simply not adopted until a server catalogue exists to fill it.
        owned.vehicles = []
        // Ownership is no longer enough for the operational cycle. `driverId` says whose
        // row it is; it cannot say whether the day happened. A simulated block carrying
        // the exact `profileId` of the proved identity — which is precisely what a
        // laboratory run by that identity produces — used to restore straight into
        // production, where it became history, a settlement and a bonus verdict. It is
        // not deleted: it stays in the blob, and it comes back the moment the laboratory
        // asks for it.
        owned.activeShift = OperationalRecordRules.shift(
            stored.activeShift,
            driverId: driverId,
            capability: capability
        )
        owned.history = OperationalRecordRules.history(
            stored.history,
            driverId: driverId,
            capability: capability
        )
        owned.incomes = stored.incomes.filter { $0.driverId == driverId }
        owned.incidents = OperationalRecordRules.incidents(
            stored.incidents,
            driverId: driverId,
            capability: capability
        )
        owned.credit = stored.credit.flatMap { $0.driverId == driverId && $0.origin == .backend ? $0 : nil }
        // No ownership field of their own — the container establishes whose they are — so
        // provenance is the only question left, and it is the one that matters: a bell
        // full of "enviado", "aprobado" and "confirmado" written by a laboratory run is
        // the most persuasive thing this app can show a driver, and the least true. The
        // rows stay on disk and come back with their own environment.
        owned.notices = NoticeRules.visible(stored.notices, authority: noticeAuthority)
        owned.supervisorReports = stored.supervisorReports
        owned.recoveryBookings = stored.recoveryBookings
        owned.notifiedBonusWeeks = stored.notifiedBonusWeeks
        return owned
    }

    private func persist() {
        persist(key: storageKey)
    }

    private func persist(key: String) {
        let state = PersistedState(
            session: session,
            enrolledAccountId: enrolledAccountId,
            vehicles: vehicles,
            activeShift: activeShift,
            history: history,
            incomes: incomes,
            incidents: incidents,
            notices: notices,
            credit: credit,
            clockOffsetMinutes: clockOffsetMinutes,
            supervisorReports: supervisorReports,
            recoveryBookings: recoveryBookings,
            notifiedBonusWeeks: notifiedBonusWeeks
        )
        do {
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .iso8601
            let data = try encoder.encode(state)
            defaults.set(data, forKey: key)
        } catch {
            print("No se pudo guardar el estado local: \(error.localizedDescription)")
        }
    }

    nonisolated private static func restore(key: String, defaults: UserDefaults) -> PersistedState? {
        guard let data = defaults.data(forKey: key) else { return nil }
        do {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            return try decoder.decode(PersistedState.self, from: data)
        } catch {
            print("No se pudo leer el estado local: \(error.localizedDescription)")
            return nil
        }
    }
}
