package com.rork.turnoevandroid.data

import com.rork.turnoevandroid.domain.ActiveShift
import com.rork.turnoevandroid.domain.CreditAccount
import com.rork.turnoevandroid.domain.Incident
import com.rork.turnoevandroid.domain.IncomeEntry
import com.rork.turnoevandroid.domain.Notice
import com.rork.turnoevandroid.domain.RecoveryBooking
import com.rork.turnoevandroid.domain.ShiftRecord
import com.rork.turnoevandroid.domain.StaffSession
import com.rork.turnoevandroid.domain.SupervisorReport
import com.rork.turnoevandroid.domain.Vehicle
import kotlinx.serialization.Serializable

/** Whole persisted session: a reopened app keeps the shift running. */
@Serializable
data class FleetState(
    /** Active session; its role is the single gate that opens an interface. */
    val session: StaffSession? = null,
    /** Credential linked to this device for biometric unlock. */
    val enrolledAccountId: String? = null,
    val vehicles: List<Vehicle> = emptyList(),
    val activeShift: ActiveShift? = null,
    val history: List<ShiftRecord> = emptyList(),
    val incomes: List<IncomeEntry> = emptyList(),
    val incidents: List<Incident> = emptyList(),
    val notices: List<Notice> = emptyList(),
    /** Used-unit credit contract; `null` while the driver has not signed one. */
    val credit: CreditAccount? = null,
    /** Reports generated by the station supervisor; they break the vehicle-care bonus. */
    val supervisorReports: List<SupervisorReport> = emptyList(),
    /** Days reserved in the bonus recovery program. */
    val recoveryBookings: List<RecoveryBooking> = emptyList(),
    /** Bonus weeks already announced, so the popup is shown only once. */
    val notifiedBonusWeeks: List<String> = emptyList(),
    /** Demo-only offset applied to the device clock so every shift rule can be reviewed. */
    val clockOffsetMinutes: Int = 0,
) {
    val isAuthenticated: Boolean get() = session != null
    val unreadNoticeCount: Int get() = notices.count { !it.read }
    val hasCredit: Boolean get() = credit != null
}
